# Generated by Django 2.0.2 on 2018-08-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurySS', '0007_auto_20180828_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimaterow',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='segment',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='segmentgrandparent',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='segmentparent',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subsegment',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subsegment',
            name='control_budget_detail_code',
            field=models.CharField(choices=[('DEL', (('DEL ADMIN', 'DEL ADMIN'), ('DEL PROG', 'DEL PROG'))), ('NON-BUDGET', 'NON-BUDGET'), ('AME', (('DEPT AME', 'DEPT AME'), ('NON-DEPT AME', 'NON-DEPT AME')))], default='NON-BUDGET', max_length=50, verbose_name='control budget detail code'),
        ),
    ]
