# Generated by Django 2.2 on 2019-07-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0009_auto_20190708_0737'),
    ]

    operations = [
        migrations.CreateModel(
            name='OSCARReturn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_l5_code', models.BigIntegerField()),
                ('sub_segment_code', models.CharField(max_length=8)),
                ('apr', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('may', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('jun', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('jul', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('aug', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('sep', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('oct', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('nov', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('dec', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('jan', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('feb', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('mar', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
            ],
            options={
                'db_table': 'forecast_oscarreturn',
                'managed': False,
            },
        ),
    ]
