# Generated by Django 2.2 on 2019-07-10 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0010_oscarreturn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oscarreturn',
            options={'managed': False, 'ordering': ['sub_segment_code']},
        ),
    ]
