# Generated by Django 2.2.4 on 2019-08-14 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0013_adireport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubSegmentUKTIMapping',
        ),
    ]
