# Generated by Django 2.0.2 on 2018-08-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gifthospitality', '0002_auto_20180828_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftsandhospitality',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotelandtravel',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
