# Generated by Django 2.0.2 on 2018-08-29 14:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('gifthospitality', '0003_auto_20180829_0723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelandtravel',
            name='cost_centre',
        ),
        migrations.RemoveField(
            model_name='hotelandtravel',
            name='natural_account_code',
        ),
        migrations.RemoveField(
            model_name='hotelandtravel',
            name='programme',
        ),
        migrations.DeleteModel(
            name='HotelAndTravel',
        ),
    ]
