# Generated by Django 2.1.2 on 2019-01-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('download_type', models.CharField(max_length=300, verbose_name='Contract Name')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
