# Generated by Django 2.1.2 on 2019-01-24 11:39

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('admintool_support', '0001_initial'), ('admintool_support', '0002_auto_20190117_0956'), ('admintool_support', '0003_auto_20190117_1359'), ('admintool_support', '0004_delete_downloadlog')]

    initial = True

    dependencies = [
    ]

    operations = [
    ]
