# Generated by Django 2.1.2 on 2019-01-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admintool_support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadlog',
            name='downloader',
            field=models.CharField(default='a', max_length=300, verbose_name='Download by'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='downloadlog',
            name='download_type',
            field=models.CharField(choices=[('CC', 'Cost Centre Hierarchy for Admin Tool'), ('NAC H', 'NAC Hierarchy for Admin Tool')], max_length=300, verbose_name='Download Type'),
        ),
    ]
