# Generated by Django 2.1.2 on 2019-01-17 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admintool_support', '0002_auto_20190117_0956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='downloadlog',
            options={'ordering': ['-download_time'], 'verbose_name': 'Download Log', 'verbose_name_plural': 'Download Logs'},
        ),
        migrations.RenameField(
            model_name='downloadlog',
            old_name='created',
            new_name='download_time',
        ),
        migrations.RemoveField(
            model_name='downloadlog',
            name='updated',
        ),
    ]
