# Generated by Django 2.1.2 on 2019-01-24 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admintool_support', '0003_auto_20190117_1359'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DownloadLog',
        ),
    ]
