# Generated by Django 2.1.5 on 2019-03-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0002_financialyear")]

    operations = [
        migrations.AddField(
            model_name="financialyear",
            name="in_use",
            field=models.BooleanField(default=False),
        )
    ]
