# Generated by Django 2.2 on 2019-07-08 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_financialyear_current_year'),
        ('core', '0002_document'),
    ]

    operations = [
    ]
