# Generated by Django 2.2 on 2019-07-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_20190708_0719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialyear',
            old_name='in_use',
            new_name='current',
        ),
        migrations.AlterField(
            model_name='admininfo',
            name='current_financial_year',
            field=models.IntegerField(),
        ),
    ]
