# Generated by Django 2.2 on 2019-08-07 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("core", "0008_remove_admininfo_current_financial_year")]

    operations = [
        migrations.AddField(
            model_name="admininfo",
            name="current_financial_year",
            field=models.ForeignKey(
                default=False,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.FinancialYear",
            ),
            preserve_default=False,
        )
    ]
