# Generated by Django 3.0.3 on 2020-12-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201130_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='sso_contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
