# Generated by Django 2.2.4 on 2019-09-04 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("core", "0010_asyncimportlog")]

    operations = [migrations.DeleteModel(name="AsyncImportLog")]
