# Generated by Django 2.2.4 on 2019-10-03 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("core", "0011_delete_asyncimportlog")]

    operations = [migrations.DeleteModel(name="AdminInfo")]
