# Generated by Django 2.2.8 on 2020-02-01 10:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0016_create_financial_years_20190917_0732'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalDocument',
            new_name='SimpleHistoryDocument',
        ),
        migrations.RenameModel(
            old_name='HistoricalEventLog',
            new_name='SimpleHistoryEventLog',
        ),
        migrations.RenameModel(
            old_name='HistoricalFinancialYear',
            new_name='SimpleHistoryFinancialYear',
        ),
    ]
