# Generated by Django 2.2.10 on 2020-05-22 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('download_type', models.CharField(choices=[('CC TRAV', 'Cost Centre  for Trainline'), ('CC', 'Cost Centre Hierarchy for Admin Tool'), ('NAC H', 'NAC Hierarchy for Admin Tool')], max_length=300, verbose_name='Download Type')),
                ('downloader', models.CharField(max_length=300, verbose_name='Download by')),
                ('download_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Download Log',
                'verbose_name_plural': 'Download Logs',
                'ordering': ['-download_time'],
            },
        ),
        migrations.CreateModel(
            name='SimpleHistoryDownloadLog',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('download_type', models.CharField(choices=[('CC TRAV', 'Cost Centre  for Trainline'), ('CC', 'Cost Centre Hierarchy for Admin Tool'), ('NAC H', 'NAC Hierarchy for Admin Tool')], max_length=300, verbose_name='Download Type')),
                ('downloader', models.CharField(max_length=300, verbose_name='Download by')),
                ('download_time', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Download Log',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
