# Generated by Django 2.1.2 on 2019-01-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DownloadLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "download_type",
                    models.CharField(
                        choices=[
                            ("CC", "Cost Centre Hierarchy for Admin Tool"),
                            ("NAC H", "NAC Hierarchy for Admin Tool"),
                        ],
                        max_length=300,
                        verbose_name="Download Type",
                    ),
                ),
                (
                    "downloader",
                    models.CharField(max_length=300, verbose_name="Download by"),
                ),
                ("download_time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Download Log",
                "verbose_name_plural": "Download Logs",
                "ordering": ["-download_time"],
            },
        )
    ]
