# Generated by Django 2.2.4 on 2019-09-04 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("downloadsupport", "0004_uploadfile")]

    operations = [migrations.DeleteModel(name="UploadFile")]
