# Generated by Django 2.2.8 on 2020-02-01 10:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('downloadsupport', '0007_auto_20200130_1135'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalDownloadLog',
            new_name='SimpleHistoryDownloadLog',
        ),
    ]
