# Generated by Django 2.1.2 on 2018-11-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gifthospitality', '0002_auto_20181109_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftsandhospitality',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='giftsandhospitality',
            name='company',
            field=models.CharField(max_length=100),
        ),
    ]
