# Generated by Django 2.1.2 on 2018-12-31 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifthospitality', '0027_giftandhospitality_grade_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftandhospitality',
            name='grade',
        ),
    ]
