# Generated by Django 2.0.2 on 2018-08-29 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0003_auto_20180829_0723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsegmentuktimapping',
            name='cost_centre',
        ),
        migrations.RemoveField(
            model_name='subsegmentuktimapping',
            name='programme',
        ),
        migrations.RemoveField(
            model_name='subsegmentuktimapping',
            name='sub_segment_code',
        ),
        migrations.DeleteModel(
            name='SubSegmentUKTIMapping',
        ),
    ]
