# Generated by Django 2.0.2 on 2018-08-29 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costcentre', '0005_auto_20180829_0936'),
        ('chartofaccountDIT', '0007_programmecode'),
        ('treasurySS', '0010_auto_20180829_1418'),
        ('forecast', '0004_auto_20180829_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubSegmentUKTIMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cost_centre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='costcentre.CostCentre')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chartofaccountDIT.ProgrammeCode')),
                ('sub_segment_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='treasurySS.SubSegment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
