# Generated by Django 2.0.2 on 2018-08-29 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0005_subsegmentuktimapping'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='adireport',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='adireport',
            name='analysis1_code',
        ),
        migrations.RemoveField(
            model_name='adireport',
            name='analysis2_code',
        ),
        migrations.RemoveField(
            model_name='adireport',
            name='cost_centre',
        ),
        migrations.RemoveField(
            model_name='adireport',
            name='natural_account_code',
        ),
        migrations.RemoveField(
            model_name='adireport',
            name='programme',
        ),
        migrations.DeleteModel(
            name='ADIReport',
        ),
    ]
