# Generated by Django 2.1.1 on 2018-10-03 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('treasuryCOA', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis1',
            fields=[
                ('active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('analysis1_code',
                 models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('analysis1_description', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Contract Reconciliation (Analysis 1)',
                'verbose_name_plural': 'Contract Reconciliations (Analysis 1)',
            },
        ),
        migrations.CreateModel(
            name='Analysis2',
            fields=[
                ('active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('analysis2_code',
                 models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('analysis2_description', models.CharField(max_length=300, verbose_name='Market')),
            ],
            options={
                'verbose_name': 'Market (Analysis 2)',
                'verbose_name_plural': 'Markets (Analysis 2)',
            },
        ),
        migrations.CreateModel(
            name='CommercialCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('commercial_category',
                 models.CharField(max_length=255, verbose_name='Commercial Category')),
                ('description', models.CharField(blank=True, max_length=5000, null=True)),
                ('approvers', models.CharField(blank=True, max_length=5000, null=True)),
            ],
            options={
                'verbose_name': 'Commercial Category',
                'verbose_name_plural': 'Commercial Categories',
            },
        ),
        migrations.CreateModel(
            name='ExpenditureCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('grouping_description',
                 models.CharField(max_length=255, verbose_name='Expenditure Category')),
                ('description', models.CharField(blank=True, max_length=5000, null=True)),
                ('further_description', models.CharField(blank=True, max_length=5000, null=True)),
            ],
            options={
                'verbose_name': 'Expenditure Category',
                'verbose_name_plural': 'Expenditure Categories',
            },
        ),
        migrations.CreateModel(
            name='NACCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('NAC_category_description',
                 models.CharField(max_length=255, verbose_name='Nac Category')),
            ],
            options={
                'verbose_name': 'Budget Grouping',
                'verbose_name_plural': 'Budget Groupings',
            },
        ),
        migrations.CreateModel(
            name='NaturalCode',
            fields=[
                ('active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('natural_account_code',
                 models.IntegerField(primary_key=True, serialize=False, verbose_name='NAC')),
                ('natural_account_code_description',
                 models.CharField(max_length=200, verbose_name='NAC Description')),
                ('used_for_budget', models.BooleanField(default=False)),
                ('account_L5_code', models.ForeignKey(blank=True, null=True,
                                                      on_delete=django.db.models.deletion.PROTECT,
                                                      to='treasuryCOA.L5Account')),
                ('commercial_category', models.ForeignKey(blank=True, null=True,
                                                          on_delete=django.db.models.deletion.PROTECT,
                                                          to='chartofaccountDIT.CommercialCategory')),
                ('expenditure_category', models.ForeignKey(blank=True, null=True,
                                                           on_delete=django.db.models.deletion.PROTECT,
                                                           to='chartofaccountDIT.ExpenditureCategory')),
            ],
            options={
                'verbose_name': 'Natural Account Code (NAC)',
                'verbose_name_plural': 'Natural Account Codes (NAC)',
            },
        ),
        migrations.CreateModel(
            name='ProgrammeCode',
            fields=[
                ('active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('programme_code',
                 models.CharField(max_length=50, primary_key=True, serialize=False,
                                  verbose_name='Programme Code')),
                ('programme_description',
                 models.CharField(max_length=100, verbose_name='Programme Name')),
                ('budget_type', models.CharField(max_length=100, verbose_name='Budget Type')),
            ],
            options={
                'verbose_name': 'Programme Code',
                'verbose_name_plural': 'Programme Codes',
            },
        ),
        migrations.AddField(
            model_name='expenditurecategory',
            name='NAC_category',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.PROTECT,
                                    to='chartofaccountDIT.NACCategory',
                                    verbose_name='Budget Grouping'),
        ),
        migrations.AddField(
            model_name='expenditurecategory',
            name='linked_budget_code',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.PROTECT,
                                    to='chartofaccountDIT.NaturalCode',
                                    verbose_name='Budget Code'),
        ),
    ]
