# Generated by Django 2.1.5 on 2019-04-02 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_financialyear_current_year'),
        ('chartofaccountDIT', '0014_historicalcommercialcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalExpenditureCategory',
            fields=[
                ('archived', models.DateTimeField(auto_now_add=True)),
                ('grouping_description', models.CharField(max_length=255, unique=True, verbose_name='Budget Category')),
                ('description', models.CharField(blank=True, max_length=5000, null=True)),
                ('further_description', models.CharField(blank=True, max_length=5000, null=True)),
                ('linked_budget_code', models.IntegerField(primary_key=True, serialize=False, verbose_name='Budget Code')),
                ('linked_budget_code_description', models.CharField(max_length=200, verbose_name='Budget Description')),
                ('NAC_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chartofaccountDIT.NACCategory', verbose_name='Budget Grouping')),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.FinancialYear')),
            ],
            options={
                'verbose_name': 'Historic Budget Category',
                'verbose_name_plural': 'Historic Budget Categories',
                'ordering': ['financial_year', 'grouping_description'],
            },
        ),
    ]
