# Generated by Django 2.0.2 on 2018-07-11 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasuryCOA', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='l5account',
            old_name='CashIndicatorCode',
            new_name='cash_indicator_code',
        ),
        migrations.RenameField(
            model_name='l5account',
            old_name='EconomicBudgetCode',
            new_name='economic_budget_code',
        ),
        migrations.RenameField(
            model_name='l5account',
            old_name='EstimatesColumnCode',
            new_name='estimates_column_code',
        ),
        migrations.RenameField(
            model_name='l5account',
            old_name='SectorCode',
            new_name='sector_code',
        ),
        migrations.RenameField(
            model_name='l5account',
            old_name='UsageCode',
            new_name='usage_code',
        ),
    ]
