# Generated by Django 2.0.2 on 2018-07-12 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasuryCOA', '0002_auto_20180711_0758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='l2account',
            old_name='account_l1_code',
            new_name='account_l1',
        ),
        migrations.RenameField(
            model_name='l3account',
            old_name='account_l2Code',
            new_name='account_l2',
        ),
        migrations.RenameField(
            model_name='l4account',
            old_name='account_l3_code',
            new_name='account_l3',
        ),
        migrations.RenameField(
            model_name='l5account',
            old_name='account_l4_code',
            new_name='account_l4',
        ),
    ]
