# Generated by Django 2.2.8 on 2020-02-01 10:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0017_auto_20200201_1043'),
        ('treasuryCOA', '0005_auto_20200130_1135'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalHistoricL5Account',
            new_name='SimpleHistoryHistoricL5Account',
        ),
        migrations.RenameModel(
            old_name='HistoricalL1Account',
            new_name='SimpleHistoryL1Account',
        ),
        migrations.RenameModel(
            old_name='HistoricalL2Account',
            new_name='SimpleHistoryL2Account',
        ),
        migrations.RenameModel(
            old_name='HistoricalL3Account',
            new_name='SimpleHistoryL3Account',
        ),
        migrations.RenameModel(
            old_name='HistoricalL4Account',
            new_name='SimpleHistoryL4Account',
        ),
        migrations.RenameModel(
            old_name='HistoricalL5Account',
            new_name='SimpleHistoryL5Account',
        ),
    ]
