# Generated by Django 2.2.10 on 2020-04-03 08:08

from django.db import migrations


def populate_end_of_month(apps, schema_editor):
    EndOfMonthModel = apps.get_model("end_of_month", "EndOfMonthStatus")
    for m in range(1, 16):
        obj = EndOfMonthModel.objects.create(archived_period_id=m)
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("end_of_month", "0001_initial"),
    ]
    operations = [migrations.RunPython(populate_end_of_month)]
