# Generated by Django 2.2.10 on 2020-04-08 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('end_of_month', '0002_auto_20200403_0808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='endofmonthstatus',
            options={'ordering': ['archived_period'], 'verbose_name': 'End of Month Archive Status', 'verbose_name_plural': 'End of Month Archive Statuses'},
        ),
        migrations.AlterModelOptions(
            name='simplehistoryendofmonthstatus',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical End of Month Archive Status'},
        ),
        migrations.AddField(
            model_name='endofmonthstatus',
            name='archived_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simplehistoryendofmonthstatus',
            name='archived_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
