# Generated by Django 2.2.10 on 2020-05-19 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0002_data_20200522'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_data_20200522'),
        ('end_of_month', '0002_auto_20200522_1028'),
    ]
    operations = [
        migrations.CreateModel(
            name='SimpleHistoryMonthlyTotalBudget',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('amount', models.BigIntegerField(default=0)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('archived_period', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='forecast.FinancialPeriod')),
                ('archived_status', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='end_of_month.EndOfMonthStatus')),
                ('financial_code', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='forecast.FinancialCode')),
                ('financial_year', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.FinancialYear')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Archived total budget',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MonthlyTotalBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('amount', models.BigIntegerField(default=0)),
                ('archived_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='end_of_month_monthlytotalbudgets', to='forecast.FinancialPeriod')),
                ('archived_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='end_of_month_monthlytotalbudgets', to='end_of_month.EndOfMonthStatus')),
                ('financial_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='end_of_month_monthlytotalbudgets', to='forecast.FinancialCode')),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.FinancialYear')),
            ],
            options={
                'verbose_name': 'Archived total budget',
                'verbose_name_plural': 'Archived total budget',
                'ordering': ['archived_status'],
                'unique_together': {('financial_code', 'archived_status')},
            },
        ),
    ]

