# Generated by Django 2.2.10 on 2020-05-27 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('end_of_month', '0007_previousadj1forecast_previousadj2forecast_previousadj3forecast_previousaprforecast_previousaugforeca'),
        ('end_of_month', '0003_data_20200522'),
    ]

    operations = [
    ]
