# Generated by Django 2.2.10 on 2020-05-22 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chartofaccountDIT', '0002_data_20200522'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimateRow',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('estimate_row_code', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='estimates row code')),
                ('estimate_row_long_name', models.CharField(max_length=255, verbose_name='estimates row long name')),
                ('sort_order', models.IntegerField(default=9999, verbose_name='sort order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('segment_code', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='segment code')),
                ('segment_long_name', models.CharField(max_length=255, verbose_name='segment long name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SegmentGrandParent',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('segment_grand_parent_code', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='segment grand parent code')),
                ('segment_grand_parent_long_name', models.CharField(max_length=255, verbose_name='segment grandparent long name')),
                ('segment_department_code', models.CharField(default='', max_length=20, verbose_name='segment department code')),
                ('segment_department_long_name', models.CharField(default='', max_length=255, verbose_name='segment department long name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SegmentParent',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('segment_parent_code', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='segment parent code')),
                ('segment_parent_long_name', models.CharField(max_length=255, verbose_name='segment parent long name')),
                ('segment_grand_parent_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='treasurySS.SegmentGrandParent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubSegment',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('sub_segment_code', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='sub segment code')),
                ('sub_segment_long_name', models.CharField(max_length=255, verbose_name='sub segment long name')),
                ('control_budget_detail_code', models.CharField(choices=[('NON-BUDGET', 'NON-BUDGET'), ('AME', (('DEPT AME', 'DEPT AME'), ('NON-DEPT AME', 'NON-DEPT AME'))), ('DEL', (('DEL ADMIN', 'DEL ADMIN'), ('DEL PROG', 'DEL PROG')))], default='NON-BUDGET', max_length=50, verbose_name='control budget detail code')),
                ('accounting_authority_code', models.CharField(max_length=255, verbose_name='accounting authority code')),
                ('accounting_authority_DetailCode', models.CharField(choices=[('VT', 'VOTED'), ('NVT', (('NON - VOTED_DEPT', 'NON - VOTED_DEPT'), ('NON-VOTED_CFER', 'NON-VOTED_CFER'), ('NON-VOTED_CF', 'NON-VOTED_CF'), ('NON-VOTED_PC', 'NON-VOTED_PC'), ('NON-VOTED_NIF', 'NON-VOTED_NIF'), ('NON-VOTED_NLF', 'NON-VOTED_NLF'), ('NON-VOTED_CEX', 'NON-VOTED_CEX'), ('NON-VOTED_SF', 'NON-VOTED_SF'), ('NON-VOTED_LG', 'NON-VOTED_LG'), ('NON-VOTED_DA', 'NON-VOTED_DA'))), ('N/A', 'N/A')], default='N/A', max_length=255, verbose_name='accounting authority detail code')),
                ('Segment_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='treasurySS.Segment')),
                ('dit_budget_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chartofaccountDIT.BudgetType', verbose_name='DIT Budget Code (used to generate the Oscar return)')),
                ('estimates_row_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='treasurySS.EstimateRow')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SimpleHistorySubSegment',
            fields=[
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('active', models.BooleanField(default=False)),
                ('sub_segment_code', models.CharField(db_index=True, max_length=8, verbose_name='sub segment code')),
                ('sub_segment_long_name', models.CharField(max_length=255, verbose_name='sub segment long name')),
                ('control_budget_detail_code', models.CharField(choices=[('NON-BUDGET', 'NON-BUDGET'), ('AME', (('DEPT AME', 'DEPT AME'), ('NON-DEPT AME', 'NON-DEPT AME'))), ('DEL', (('DEL ADMIN', 'DEL ADMIN'), ('DEL PROG', 'DEL PROG')))], default='NON-BUDGET', max_length=50, verbose_name='control budget detail code')),
                ('accounting_authority_code', models.CharField(max_length=255, verbose_name='accounting authority code')),
                ('accounting_authority_DetailCode', models.CharField(choices=[('VT', 'VOTED'), ('NVT', (('NON - VOTED_DEPT', 'NON - VOTED_DEPT'), ('NON-VOTED_CFER', 'NON-VOTED_CFER'), ('NON-VOTED_CF', 'NON-VOTED_CF'), ('NON-VOTED_PC', 'NON-VOTED_PC'), ('NON-VOTED_NIF', 'NON-VOTED_NIF'), ('NON-VOTED_NLF', 'NON-VOTED_NLF'), ('NON-VOTED_CEX', 'NON-VOTED_CEX'), ('NON-VOTED_SF', 'NON-VOTED_SF'), ('NON-VOTED_LG', 'NON-VOTED_LG'), ('NON-VOTED_DA', 'NON-VOTED_DA'))), ('N/A', 'N/A')], default='N/A', max_length=255, verbose_name='accounting authority detail code')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('Segment_code', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasurySS.Segment')),
                ('dit_budget_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='chartofaccountDIT.BudgetType', verbose_name='DIT Budget Code (used to generate the Oscar return)')),
                ('estimates_row_code', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasurySS.EstimateRow')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical sub segment',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SimpleHistorySegmentParent',
            fields=[
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('active', models.BooleanField(default=False)),
                ('segment_parent_code', models.CharField(db_index=True, max_length=8, verbose_name='segment parent code')),
                ('segment_parent_long_name', models.CharField(max_length=255, verbose_name='segment parent long name')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('segment_grand_parent_code', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasurySS.SegmentGrandParent')),
            ],
            options={
                'verbose_name': 'historical segment parent',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SimpleHistorySegmentGrandParent',
            fields=[
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('active', models.BooleanField(default=False)),
                ('segment_grand_parent_code', models.CharField(db_index=True, max_length=8, verbose_name='segment grand parent code')),
                ('segment_grand_parent_long_name', models.CharField(max_length=255, verbose_name='segment grandparent long name')),
                ('segment_department_code', models.CharField(default='', max_length=20, verbose_name='segment department code')),
                ('segment_department_long_name', models.CharField(default='', max_length=255, verbose_name='segment department long name')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical segment grand parent',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SimpleHistorySegment',
            fields=[
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('active', models.BooleanField(default=False)),
                ('segment_code', models.CharField(db_index=True, max_length=8, verbose_name='segment code')),
                ('segment_long_name', models.CharField(max_length=255, verbose_name='segment long name')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('segment_parent_code', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='treasurySS.SegmentParent')),
            ],
            options={
                'verbose_name': 'historical segment',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SimpleHistoryEstimateRow',
            fields=[
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('active', models.BooleanField(default=False)),
                ('estimate_row_code', models.CharField(db_index=True, max_length=8, verbose_name='estimates row code')),
                ('estimate_row_long_name', models.CharField(max_length=255, verbose_name='estimates row long name')),
                ('sort_order', models.IntegerField(default=9999, verbose_name='sort order')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical estimate row',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='segment',
            name='segment_parent_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='treasurySS.SegmentParent'),
        ),
    ]
