# Generated by Django 2.1.2 on 2018-11-23 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("treasurySS", "0015_auto_20181114_1706"),
        ("treasurySS", "0016_auto_20181109_0823"),
    ]

    operations = []
