# Generated by Django 2.2 on 2019-06-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("treasurySS", "0098_subsegment_dit_budget_type")]

    operations = [
        migrations.RemoveField(model_name="subsegment", name="dit_budget_type"),
        migrations.AlterField(
            model_name="subsegment",
            name="control_budget_detail_code",
            field=models.CharField(
                choices=[
                    ("DEL", (("DEL ADMIN", "DEL ADMIN"), ("DEL PROG", "DEL PROG"))),
                    ("NON-BUDGET", "NON-BUDGET"),
                    (
                        "AME",
                        (("DEPT AME", "DEPT AME"), ("NON-DEPT AME", "NON-DEPT AME")),
                    ),
                ],
                default="NON-BUDGET",
                max_length=50,
                verbose_name="control budget detail code",
            ),
        ),
    ]
