# Generated by Django 2.2 on 2019-07-08 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasurySS', '0056_auto_20190227_1129'),
        ('treasurySS', '0105_auto_20190703_0751'),
    ]

    operations = [
    ]
