# Generated by Django 2.2 on 2019-07-29 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("treasurySS", "0106_auto_20190719_1637"),
        ("treasurySS", "0112_auto_20190710_1429"),
    ]

    operations = []
