# Generated by Django 2.2.4 on 2019-11-05 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasurySS', '0136_auto_20191101_1043'),
        ('treasurySS', '0136_auto_20191105_1342'),
    ]

    operations = [
    ]
