# Generated by Django 2.0.2 on 2018-08-21 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('treasuryCOA', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis1',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('analysis1_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('analysis1_description', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Analysis Codes 1',
            },
        ),
        migrations.CreateModel(
            name='Analysis2',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('analysis2_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('analysis2_description', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Analysis Codes 2',
            },
        ),
        migrations.CreateModel(
            name='ExpenditureCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('grouping_description', models.CharField(max_length=255, verbose_name='Description')),
                ('description', models.CharField(blank=True, max_length=5000, null=True)),
                ('further_description', models.CharField(blank=True, max_length=5000, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NACCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('NAC_category_description', models.CharField(max_length=255, verbose_name='Nac Category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NaturalCode',
            fields=[
                ('natural_account_code', models.IntegerField(primary_key=True, serialize=False, verbose_name='NAC')),
                ('natural_account_code_description', models.CharField(max_length=200, verbose_name='NAC Description')),
                ('used_for_budget', models.BooleanField(default=False)),
                ('used_by_DIT', models.BooleanField(default=False)),
                ('account_L5_code',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                   to='treasuryCOA.L5Account')),
                ('expenditure_category',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                   to='chartofaccountDIT.ExpenditureCategory', verbose_name='Budget Category')),
            ],
        ),
        migrations.AddField(
            model_name='expenditurecategory',
            name='NAC_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='chartofaccountDIT.NACCategory'),
        ),
        migrations.AddField(
            model_name='expenditurecategory',
            name='linked_budget_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='chartofaccountDIT.NaturalCode', verbose_name='Budget Code'),
        ),
    ]
