# Generated by Django 2.0.2 on 2018-07-16 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccountDIT', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naturalcode',
            name='account_L5_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='treasuryCOA.L5Account'),
        ),
    ]
