# Generated by Django 2.0.2 on 2018-08-22 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('chartofaccountDIT', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('commercial_category', models.CharField(max_length=255, verbose_name='Commercial Category')),
                ('description', models.CharField(blank=True, max_length=5000, null=True)),
                ('approvers', models.CharField(blank=True, max_length=5000, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='expenditurecategory',
            name='NAC_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='chartofaccountDIT.NACCategory', verbose_name='Budget Grouping'),
        ),
        migrations.AlterField(
            model_name='expenditurecategory',
            name='grouping_description',
            field=models.CharField(max_length=255, verbose_name='Expenditure Category'),
        ),
        migrations.AlterField(
            model_name='naturalcode',
            name='expenditure_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='chartofaccountDIT.ExpenditureCategory'),
        ),
        migrations.AddField(
            model_name='naturalcode',
            name='commercial_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='chartofaccountDIT.CommercialCategory'),
        ),
    ]
