# Generated by Django 2.0.2 on 2018-08-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('chartofaccountDIT', '0002_auto_20180822_0745'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysis2',
            options={'verbose_name_plural': 'Analysis 2 (Markets)'},
        ),
        migrations.AlterModelOptions(
            name='commercialcategory',
            options={'verbose_name_plural': 'Commercial Categories'},
        ),
        migrations.AlterModelOptions(
            name='expenditurecategory',
            options={'verbose_name_plural': 'Expenditure Categories'},
        ),
        migrations.AlterModelOptions(
            name='naccategory',
            options={'verbose_name_plural': 'Budget Groupings'},
        ),
        migrations.RenameField(
            model_name='naturalcode',
            old_name='used_by_DIT',
            new_name='active',
        ),
        migrations.AlterField(
            model_name='analysis2',
            name='analysis2_description',
            field=models.CharField(max_length=300, verbose_name='Market'),
        ),
    ]
