# Generated by Django 2.0.2 on 2018-08-28 09:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccountDIT', '0003_auto_20180828_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='naturalcode',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='naturalcode',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
