# Generated by Django 2.0.2 on 2018-07-19 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccountDIT', '0003_auto_20180719_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='naccategory',
            name='linked_budget_code',
        ),
        migrations.AddField(
            model_name='nacdashboardgrouping',
            name='linked_budget_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chartofaccountDIT.NaturalCode'),
        ),
    ]
