# Generated by Django 2.0.2 on 2018-08-29 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccountDIT', '0005_auto_20180829_0723'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysis1',
            options={'verbose_name': 'Contract Reconciliation (Analysis 1)', 'verbose_name_plural': 'Contract Reconciliations (Analysis 1)'},
        ),
        migrations.AlterModelOptions(
            name='analysis2',
            options={'verbose_name': 'Market (Analysis 2)', 'verbose_name_plural': 'Markets (Analysis 2)'},
        ),
        migrations.AlterModelOptions(
            name='commercialcategory',
            options={'verbose_name': 'Commercial Category', 'verbose_name_plural': 'Commercial Categories'},
        ),
        migrations.AlterModelOptions(
            name='expenditurecategory',
            options={'verbose_name': 'Expenditure Category', 'verbose_name_plural': 'Expenditure Categories'},
        ),
        migrations.AlterModelOptions(
            name='naccategory',
            options={'verbose_name': 'Budget Grouping', 'verbose_name_plural': 'Budget Groupings'},
        ),
        migrations.AlterModelOptions(
            name='naturalcode',
            options={'verbose_name': 'Natural Account Code (NAC)', 'verbose_name_plural': 'Natural Account Codes (NAC)'},
        ),
    ]
