# Generated by Django 2.0.2 on 2018-08-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccountDIT', '0005_auto_20180810_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naturalcode',
            name='natural_account_code',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='NAC'),
        ),
        migrations.AlterField(
            model_name='naturalcode',
            name='natural_account_code_description',
            field=models.CharField(max_length=200, verbose_name='NAC Description'),
        ),
    ]
