# Generated by Django 2.0.2 on 2018-08-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccountDIT', '0006_auto_20180829_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammeCode',
            fields=[
                ('active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('programme_code', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Programme Code')),
                ('programme_description', models.CharField(max_length=100, verbose_name='Programme Name')),
                ('budget_type', models.CharField(max_length=100, verbose_name='Budget Type')),
            ],
            options={
                'verbose_name': 'Programme Code',
                'verbose_name_plural': 'Programme Codes',
            },
        ),
    ]
