# Generated by Django 2.0.2 on 2018-06-11 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('costcentre', '0001_initial'),
        ('chartofaccountDIT', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPayModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('pay_rise', models.DecimalField(decimal_places=2, max_digits=18)),
                ('Vacancy', models.DecimalField(decimal_places=2, max_digits=18)),
                ('GAE', models.DecimalField(decimal_places=2, max_digits=18)),
                ('SCS_percent', models.DecimalField(decimal_places=2, max_digits=18)),
                ('SCS_number', models.DecimalField(decimal_places=2, max_digits=18)),
                ('indicative_budget', models.IntegerField()),
                ('group_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='costcentre.DepartmentalGroup')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('grade', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PayCostHeadCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_number', models.IntegerField()),
                ('year', models.IntegerField()),
                ('apr', models.BooleanField()),
                ('may', models.BooleanField()),
                ('jun', models.BooleanField()),
                ('jul', models.BooleanField()),
                ('aug', models.BooleanField()),
                ('sep', models.BooleanField()),
                ('oct', models.BooleanField()),
                ('nov', models.BooleanField()),
                ('dec', models.BooleanField()),
                ('jan', models.BooleanField()),
                ('feb', models.BooleanField()),
                ('mar', models.BooleanField()),
                ('cost_centre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='costcentre.CostCentre')),
                ('natural_account_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chartofaccountDIT.NaturalCode')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='costcentre.Programme')),
            ],
        ),
        migrations.CreateModel(
            name='PayModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('apr', models.DecimalField(decimal_places=1, max_digits=18)),
                ('may', models.DecimalField(decimal_places=1, max_digits=18)),
                ('jun', models.DecimalField(decimal_places=1, max_digits=18)),
                ('jul', models.DecimalField(decimal_places=1, max_digits=18)),
                ('aug', models.DecimalField(decimal_places=1, max_digits=18)),
                ('sep', models.DecimalField(decimal_places=1, max_digits=18)),
                ('oct', models.DecimalField(decimal_places=1, max_digits=18)),
                ('nov', models.DecimalField(decimal_places=1, max_digits=18)),
                ('dec', models.DecimalField(decimal_places=1, max_digits=18)),
                ('jan', models.DecimalField(decimal_places=1, max_digits=18)),
                ('feb', models.DecimalField(decimal_places=1, max_digits=18)),
                ('mar', models.DecimalField(decimal_places=1, max_digits=18)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payroll.Grade')),
                ('group_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='costcentre.DepartmentalGroup')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryMonthlyAverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_type', models.CharField(choices=[('CC', 'CostCentre'), ('DIR', 'Directorate'), ('DG', 'DepartmentalGroup')], max_length=50)),
                ('average_by', models.CharField(max_length=50)),
                ('average_value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payroll.Grade')),
            ],
        ),
        migrations.CreateModel(
            name='VacanciesHeadCount',
            fields=[
                ('slot_code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('apr', models.BooleanField()),
                ('may', models.BooleanField()),
                ('jun', models.BooleanField()),
                ('jul', models.BooleanField()),
                ('aug', models.BooleanField()),
                ('sep', models.BooleanField()),
                ('oct', models.BooleanField()),
                ('nov', models.BooleanField()),
                ('dec', models.BooleanField()),
                ('jan', models.BooleanField()),
                ('feb', models.BooleanField()),
                ('mar', models.BooleanField()),
                ('HR_reason', models.CharField(max_length=50)),
                ('cost_centre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='costcentre.CostCentre')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='costcentre.Programme')),
                ('vacancy_grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payroll.Grade')),
            ],
        ),
    ]
