# Generated by Django 2.0.2 on 2018-08-16 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_auto_20180816_1111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ditpeople',
            options={'verbose_name': 'DIT People'},
        ),
    ]
