# Generated by Django 2.0.2 on 2018-08-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('payroll', '0002_auto_20180828_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminpaymodel',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paycostheadcount',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymodel',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vacanciesheadcount',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ditpeople',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
