# Generated by Django 2.0.2 on 2018-08-29 14:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('payroll', '0003_auto_20180829_0723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paycostheadcount',
            name='cost_centre',
        ),
        migrations.RemoveField(
            model_name='paycostheadcount',
            name='natural_account_code',
        ),
        migrations.RemoveField(
            model_name='paycostheadcount',
            name='programme',
        ),
        migrations.RemoveField(
            model_name='vacanciesheadcount',
            name='cost_centre',
        ),
        migrations.RemoveField(
            model_name='vacanciesheadcount',
            name='programme',
        ),
        migrations.RemoveField(
            model_name='vacanciesheadcount',
            name='vacancy_grade',
        ),
        migrations.DeleteModel(
            name='PayCostHeadCount',
        ),
        migrations.DeleteModel(
            name='VacanciesHeadCount',
        ),
    ]
