# Generated by Django 2.0.2 on 2018-08-20 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_auto_20180816_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ditpeople',
            name='id',
        ),
        migrations.AddField(
            model_name='ditpeople',
            name='EmployeeNumber',
            field=models.CharField(default='Z', max_length=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ditpeople',
            name='grade',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='payroll.Grade'),
        ),
    ]
