# Generated by Django 2.0.2 on 2018-08-20 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_auto_20180820_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ditpeople',
            old_name='EmployeeNumber',
            new_name='employee_number',
        ),
        migrations.AlterField(
            model_name='ditpeople',
            name='cost_centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='costcentre.CostCentre'),
        ),
        migrations.AlterField(
            model_name='ditpeople',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payroll.Grade'),
        ),
    ]
