# Generated by Django 2.0.2 on 2018-08-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_auto_20180820_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ditpeople',
            name='isbusinesspartner',
            field=models.BooleanField(default=False, verbose_name='Business Partner'),
        ),
        migrations.AlterField(
            model_name='ditpeople',
            name='isdirector',
            field=models.BooleanField(default=False, verbose_name='General Director/Director/Deputy Director'),
        ),
    ]
