# Generated by Django 2.1.2 on 2018-12-03 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_auto_20181008_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ditpeople',
            name='email',
        ),
        migrations.RemoveField(
            model_name='ditpeople',
            name='isbusinesspartner',
        ),
        migrations.RemoveField(
            model_name='ditpeople',
            name='isdirector',
        ),
    ]
