# Generated by Django 2.1.2 on 2018-12-11 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("payroll", "0003_auto_20181203_1524")]

    operations = [
        migrations.AlterModelOptions(
            name="ditpeople",
            options={
                "ordering": ["surname"],
                "verbose_name": "DIT People",
                "verbose_name_plural": "DIT People",
            },
        )
    ]
