# Generated by Django 2.2.10 on 2020-04-02 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_ditgroup_simplehistoryditgroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ditgroup',
            options={'ordering': ['cost_centre'], 'verbose_name': 'DIT Group', 'verbose_name_plural': 'DIT People'},
        ),
        migrations.AlterModelOptions(
            name='simplehistoryditgroup',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical DIT Group'},
        ),
    ]
