# Generated by Django 2.2.10 on 2020-04-07 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gifthospitality', '0034_auto_20200407_1220'),
        ('payroll', '0008_auto_20200402_0753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simplehistoryditgroup',
            name='cost_centre',
        ),
        migrations.RemoveField(
            model_name='simplehistoryditgroup',
            name='directorate_code',
        ),
        migrations.RemoveField(
            model_name='simplehistoryditgroup',
            name='group_code',
        ),
        migrations.RemoveField(
            model_name='simplehistoryditgroup',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='simplehistorygrade',
            name='history_user',
        ),
        migrations.AlterField(
            model_name='ditpeople',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gifthospitality.Grade'),
        ),
        migrations.AlterField(
            model_name='paymodel',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gifthospitality.Grade'),
        ),
        migrations.AlterField(
            model_name='salarymonthlyaverage',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gifthospitality.Grade'),
        ),
        migrations.AlterField(
            model_name='simplehistoryditpeople',
            name='grade',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gifthospitality.Grade'),
        ),
        migrations.AlterField(
            model_name='simplehistorypaymodel',
            name='grade',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gifthospitality.Grade'),
        ),
        migrations.AlterField(
            model_name='simplehistorysalarymonthlyaverage',
            name='grade',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gifthospitality.Grade'),
        ),
        migrations.DeleteModel(
            name='DITGroup',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.DeleteModel(
            name='SimpleHistoryDITGroup',
        ),
        migrations.DeleteModel(
            name='SimpleHistoryGrade',
        ),
    ]
