# Generated by Django 2.1.1 on 2018-10-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('chartofaccountDIT', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialcategory',
            name='commercial_category',
            field=models.CharField(max_length=255, unique=True,
                                   verbose_name='Commercial Category'),
        ),
        migrations.AlterField(
            model_name='expenditurecategory',
            name='grouping_description',
            field=models.CharField(max_length=255, unique=True,
                                   verbose_name='Expenditure Category'),
        ),
        migrations.AlterField(
            model_name='naccategory',
            name='NAC_category_description',
            field=models.CharField(max_length=255, unique=True, verbose_name='Budget Grouping'),
        ),
    ]
