# Generated by Django 2.2.13 on 2020-08-18 15:11

from django.db import migrations, models
import django.db.models.deletion


def insert_budget_type_fk(apps, schema_editor):
    ProgrammeCode = apps.get_model("chartofaccountDIT", "ArchivedProgrammeCode")
    BudgetType = apps.get_model("chartofaccountDIT", "BudgetType")
    for programme in ProgrammeCode.objects.all():
        programme.budget_type_fk = BudgetType.objects.get(
            budget_type=programme.budget_type
        )
        programme.save()


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccountDIT', '0002_data_20200522'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedprogrammecode',
            name='budget_type_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chartofaccountDIT.BudgetType', verbose_name='Budget Type'),
        ),
        migrations.AddField(
            model_name='simplehistoryarchivedprogrammecode',
            name='budget_type_fk',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='chartofaccountDIT.BudgetType', verbose_name='Budget Type'),
        ),
        migrations.RunPython(insert_budget_type_fk),

    ]
