# Generated by Django 2.2.13 on 2020-08-20 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccountDIT', '0003_auto_20200818_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivedprogrammecode',
            name='budget_type',
        ),
        migrations.RemoveField(
            model_name='simplehistoryarchivedprogrammecode',
            name='budget_type',
        ),

        migrations.RenameField(
            model_name='simplehistoryprogrammecode',
            old_name='budget_type_fk',
            new_name='budget_type',
        ),
        migrations.RenameField(
            model_name='archivedprogrammecode',
            old_name='budget_type_fk',
            new_name='budget_type',
        ),
        migrations.RenameField(
            model_name='programmecode',
            old_name='budget_type_fk',
            new_name='budget_type'
        ),
        migrations.RenameField(
            model_name='simplehistoryarchivedprogrammecode',
            old_name='budget_type_fk',
            new_name='budget_type',
        ),
        migrations.AlterField(
            model_name='programmecode',
            name='budget_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chartofaccountdit_programmecode', to='chartofaccountDIT.BudgetType', verbose_name='Budget Type'),
        ),
        migrations.AlterField(
            model_name='archivedanalysis1',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chartofaccountdit_archivedanalysis1', to='core.FinancialYear'),
        ),
        migrations.AlterField(
            model_name='archivedanalysis2',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chartofaccountdit_archivedanalysis2', to='core.FinancialYear'),
        ),
        migrations.AlterField(
            model_name='archivedcommercialcategory',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chartofaccountdit_archivedcommercialcategory', to='core.FinancialYear'),
        ),
        migrations.AlterField(
            model_name='archivedexpenditurecategory',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chartofaccountdit_archivedexpenditurecategory', to='core.FinancialYear'),
        ),
        migrations.AlterField(
            model_name='archivedfcomapping',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chartofaccountdit_archivedfcomapping', to='core.FinancialYear'),
        ),
        migrations.AlterField(
            model_name='archivedinterentity',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chartofaccountdit_archivedinterentity', to='core.FinancialYear'),
        ),
        migrations.AlterField(
            model_name='archivednaturalcode',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chartofaccountdit_archivednaturalcode', to='core.FinancialYear'),
        ),
        migrations.AlterField(
            model_name='archivedprogrammecode',
            name='budget_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chartofaccountdit_archivedprogrammecode', to='chartofaccountDIT.BudgetType', verbose_name='Budget Type'),
        ),
        migrations.AlterField(
            model_name='archivedprogrammecode',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chartofaccountdit_archivedprogrammecode', to='core.FinancialYear'),
        ),
        migrations.AlterField(
            model_name='archivedprojectcode',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chartofaccountdit_archivedprojectcode', to='core.FinancialYear'),
        ),
        migrations.AlterField(
            model_name='simplehistoryarchivedprogrammecode',
            name='budget_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='chartofaccountDIT.BudgetType', verbose_name='Budget Type'),
        ),
    ]
