# Generated by Django 2.1.2 on 2018-11-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("chartofaccountDIT", "0004_interentity_cpid")]

    operations = [
        migrations.AddField(
            model_name="analysis1",
            name="pc_reference",
            field=models.CharField(
                default="", max_length=300, verbose_name="PC Reference"
            ),
        ),
        migrations.AddField(
            model_name="analysis1",
            name="supplier",
            field=models.CharField(default="", max_length=300, verbose_name="Supplier"),
        ),
        migrations.AlterField(
            model_name="analysis1",
            name="analysis1_code",
            field=models.CharField(
                max_length=50,
                primary_key=True,
                serialize=False,
                verbose_name="Contract Code",
            ),
        ),
        migrations.AlterField(
            model_name="analysis1",
            name="analysis1_description",
            field=models.CharField(max_length=300, verbose_name="Contract Name"),
        ),
        migrations.AlterField(
            model_name="interentity",
            name="cpid",
            field=models.CharField(
                max_length=10, verbose_name="CPID (Departmental Code No.)"
            ),
        ),
    ]
