# Generated by Django 2.2.13 on 2020-09-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccountDIT', '0005_auto_20200828_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis1',
            name='pc_reference',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='PC Reference'),
        ),
        migrations.AlterField(
            model_name='analysis1',
            name='supplier',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='archivedanalysis1',
            name='pc_reference',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='PC Reference'),
        ),
        migrations.AlterField(
            model_name='archivedanalysis1',
            name='supplier',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='simplehistoryanalysis1',
            name='pc_reference',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='PC Reference'),
        ),
        migrations.AlterField(
            model_name='simplehistoryanalysis1',
            name='supplier',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='simplehistoryarchivedanalysis1',
            name='pc_reference',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='PC Reference'),
        ),
        migrations.AlterField(
            model_name='simplehistoryarchivedanalysis1',
            name='supplier',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Supplier'),
        ),
    ]
