# Generated by Django 2.2.13 on 2020-09-25 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccountDIT', '0007_auto_20200924_0931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivedcommercialcategory',
            options={'ordering': ['financial_year', 'commercial_category'], 'verbose_name': 'Archived Commercial Category', 'verbose_name_plural': 'Archived Commercial Categories'},
        ),
        migrations.AlterModelOptions(
            name='archivedexpenditurecategory',
            options={'ordering': ['financial_year', 'grouping_description'], 'verbose_name': 'Archived Budget Category', 'verbose_name_plural': 'Archived Budget Categories'},
        ),
        migrations.AlterModelOptions(
            name='archivedfcomapping',
            options={'ordering': ['financial_year', 'fco_code'], 'verbose_name': 'Archived FCO Mapping', 'verbose_name_plural': 'Archived FCO Mappings'},
        ),
        migrations.AlterModelOptions(
            name='archivedinterentity',
            options={'ordering': ['financial_year', 'l2_value'], 'verbose_name': 'Archived Inter-Entity', 'verbose_name_plural': 'Archived Inter-Entities'},
        ),
        migrations.AlterModelOptions(
            name='archivednaturalcode',
            options={'ordering': ['financial_year', 'natural_account_code'], 'verbose_name': 'Archived Natural Account Code (NAC)', 'verbose_name_plural': 'Archived Natural Account Codes (NAC)'},
        ),
        migrations.AlterModelOptions(
            name='archivedprogrammecode',
            options={'ordering': ['financial_year', 'programme_code'], 'verbose_name': 'Archived Programme Code', 'verbose_name_plural': 'Archived Programme Codes'},
        ),
        migrations.AlterModelOptions(
            name='archivedprojectcode',
            options={'ordering': ['financial_year', 'project_code'], 'verbose_name': 'Archived Project', 'verbose_name_plural': 'Archived Projects'},
        ),
        migrations.AlterModelOptions(
            name='simplehistoryarchivedcommercialcategory',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Archived Commercial Category'},
        ),
        migrations.AlterModelOptions(
            name='simplehistoryarchivedexpenditurecategory',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Archived Budget Category'},
        ),
        migrations.AlterModelOptions(
            name='simplehistoryarchivedfcomapping',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Archived FCO Mapping'},
        ),
        migrations.AlterModelOptions(
            name='simplehistoryarchivedinterentity',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Archived Inter-Entity'},
        ),
        migrations.AlterModelOptions(
            name='simplehistoryarchivednaturalcode',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Archived Natural Account Code (NAC)'},
        ),
        migrations.AlterModelOptions(
            name='simplehistoryarchivedprogrammecode',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Archived Programme Code'},
        ),
        migrations.AlterModelOptions(
            name='simplehistoryarchivedprojectcode',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Archived Project'},
        ),
    ]
