# Generated by Django 2.1.2 on 2018-11-23 08:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('chartofaccountDIT', '0007_naturalcode_account_l5_code_upload'),
        ('chartofaccountDIT', '0006_auto_20181108_1706'),
    ]

    operations = [
    ]
