# Generated by Django 2.1.5 on 2019-04-02 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("chartofaccountDIT", "0015_historicalexpenditurecategory")]

    operations = [
        migrations.RemoveField(
            model_name="historicalexpenditurecategory", name="NAC_category"
        ),
        migrations.RemoveField(
            model_name="historicalexpenditurecategory", name="financial_year"
        ),
        migrations.DeleteModel(name="HistoricalExpenditureCategory"),
    ]
