# Generated by Django 2.1.5 on 2019-04-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccountDIT', '0019_historicalexpenditurecategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalexpenditurecategory',
            name='NAC_category',
            field=models.CharField(max_length=255, verbose_name='Budget Grouping'),
        ),
    ]
