# Generated by Django 2.1.5 on 2019-04-03 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccountDIT', '0021_historicalinterentity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalinterentity',
            name='financial_year',
        ),
        migrations.RemoveField(
            model_name='historicalinterentity',
            name='l1_value',
        ),
        migrations.DeleteModel(
            name='HistoricalInterEntity',
        ),
    ]
