# Generated by Django 2.1.5 on 2019-04-03 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_financialyear_current_year'),
        ('chartofaccountDIT', '0022_auto_20190403_0814'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalInterEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.DateTimeField(auto_now_add=True)),
                ('l2_description', models.CharField(max_length=100, verbose_name='ORACLE - Inter Entity Description')),
                ('cpid', models.CharField(max_length=10, verbose_name='Treasury - CPID (Departmental Code No.)')),
                ('l2_value', models.CharField(max_length=10, verbose_name='ORACLE - Inter Entity Code')),
                ('l1_value', models.CharField(max_length=10, verbose_name='Government Body')),
                ('l1_description', models.CharField(max_length=100, verbose_name='Government Body Description')),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.FinancialYear')),
            ],
            options={
                'verbose_name': 'Historic Inter-Entity',
                'verbose_name_plural': 'Historic Inter-Entities',
                'ordering': ['financial_year', 'l2_value'],
            },
        ),
    ]
