# Generated by Django 2.1.5 on 2019-04-03 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_financialyear_current_year'),
        ('chartofaccountDIT', '0027_auto_20190403_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAnalysis2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.DateTimeField(auto_now_add=True)),
                ('analysis2_description', models.CharField(max_length=300, verbose_name='Market')),
                ('analysis2_code', models.CharField(max_length=50, verbose_name='Contract Code')),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.FinancialYear')),
            ],
            options={
                'verbose_name': 'Historic Market (Analysis 2)',
                'verbose_name_plural': 'HistoricMarkets (Analysis 2)',
                'ordering': ['financial_year', 'analysis2_code'],
            },
        ),
    ]
