# Generated by Django 2.1.5 on 2019-04-03 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccountDIT', '0029_historicalnaturalcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalNaturalCode',
        ),
    ]
