# Generated by Django 2.1.5 on 2019-04-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("chartofaccountDIT", "0032_auto_20190403_1354")]

    operations = [
        migrations.AlterModelOptions(
            name="historicalfcomapping",
            options={
                "ordering": ["financial_year", "fco_code"],
                "verbose_name": "Historic FCO Mapping",
                "verbose_name_plural": "Historic FCO Mappings",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalnaturalcode",
            options={
                "ordering": ["financial_year", "natural_account_code"],
                "verbose_name": "Historic Natural Account Code (NAC)",
                "verbose_name_plural": "Historic Natural Account Codes (NAC)",
            },
        ),
        migrations.AddField(
            model_name="historicalanalysis1",
            name="active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalanalysis2",
            name="active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalcommercialcategory",
            name="active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalexpenditurecategory",
            name="active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalfcomapping",
            name="active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalinterentity",
            name="active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalprogrammecode",
            name="active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalprojectcode",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
