# Generated by Django 2.2 on 2019-06-21 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccountDIT', '0038_budgettype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BudgetType',
        ),
    ]
