# Generated by Django 2.2 on 2019-06-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("chartofaccountDIT", "0039_delete_budgettype")]

    operations = [
        migrations.CreateModel(
            name="BudgetType",
            fields=[
                (
                    "budget_key",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Key",
                    ),
                ),
                (
                    "budget_type",
                    models.CharField(max_length=100, verbose_name="Budget Type"),
                ),
            ],
        )
    ]
