# Generated by Django 2.2 on 2019-06-21 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccountDIT', '0042_remove_programmecode_budget_type_fk'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BudgetType',
        ),
    ]
