# Generated by Django 2.2 on 2019-06-21 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccountDIT', '0044_budgettype'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmecode',
            name='budget_type_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chartofaccountDIT.BudgetType', verbose_name='Budget Type'),
        ),
    ]
