# Generated by Django 2.2 on 2019-06-24 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("chartofaccountDIT", "0047_auto_20190624_0719")]

    operations = [
        migrations.RemoveField(model_name="programmecode", name="budget_type")
    ]
