# Generated by Django 2.2.4 on 2019-11-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccountDIT', '0049_auto_20191003_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='naturalcode',
            name='economic_budget_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Expenditure Type'),
        ),
    ]
