# Generated by Django 2.2.4 on 2019-11-06 12:35

from django.db import migrations


def update_economic_budget_code(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    NaturalCode = apps.get_model('chartofaccountDIT', 'NaturalCode')
    q = NaturalCode.objects.filter(account_L5_code__isnull=False)
    for obj in q:
        obj.economic_budget_code = obj.account_L5_code.economic_budget_code
        obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ('chartofaccountDIT', '0050_naturalcode_economic_budget_code'),
    ]

    operations = [migrations.RunPython(update_economic_budget_code)]
