# Generated by Django 2.2.10 on 2020-03-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccountDIT', '0050_update_budget_types_and_natural_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='naccategory',
            name='NAC_category_display_order',
            field=models.IntegerField(blank=True, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='simplehistorynaccategory',
            name='NAC_category_display_order',
            field=models.IntegerField(blank=True, null=True),
            preserve_default=False,
        ),
    ]
