# Generated by Django 2.2.8 on 2020-02-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccountDIT', '0051_auto_20191106_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgettype',
            name='budget_type_edit_display_order',
            field=models.IntegerField(default=99),
        ),
    ]
