# Generated by Django 2.2.4 on 2019-10-03 13:17

from django.db import migrations, models


def update_budget_types(apps, schema_editor):
    BudgetType = apps.get_model("chartofaccountDIT", "BudgetType")
    b = BudgetType.objects.get(budget_type_key="DEL")
    b.budget_type_edit_display_order = 2
    b.save()
    b = BudgetType.objects.get(budget_type_key="AME", budget_type="Programme AME")
    b.budget_type_edit_display_order = 3
    b.save()
    b = BudgetType.objects.get(budget_type_key="ADMIN", budget_type="Admin")
    b.budget_type_edit_display_order = 1
    b.save()


class Migration(migrations.Migration):
    dependencies = [("chartofaccountDIT", "0052_budgettype_budget_type_edit_display_order")]

    operations = [
        migrations.RunPython(update_budget_types),
    ]
