# Generated by Django 2.2.10 on 2020-04-03 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccountDIT', '0052_auto_20200305_0846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='naccategory',
            options={'ordering': ['NAC_category_display_order'], 'verbose_name': 'Budget Grouping', 'verbose_name_plural': 'Budget Groupings'},
        ),
    ]
