# Generated by Django 2.1.5 on 2019-02-06 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("costcentre", "0015_auto_20181123_0859"),
        ("chartofaccountDIT", "0010_fcomapping"),
        ("forecast", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Budget",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=False)),
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Budget ID"
                    ),
                ),
                (
                    "analysis1_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="chartofaccountDIT.Analysis1",
                    ),
                ),
                (
                    "analysis2_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="chartofaccountDIT.Analysis2",
                    ),
                ),
                (
                    "cost_centre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="costcentre.CostCentre",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FinancialPeriod",
            fields=[
                (
                    "financial_period_code",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("period_long_name", models.CharField(max_length=20)),
                ("period_short_name", models.CharField(max_length=5)),
                ("period_calendar_code", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="FinancialYear",
            fields=[
                (
                    "financial_year",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("financial_year_display", models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name="MonthlyFigure",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=False)),
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Monthly ID"
                    ),
                ),
                (
                    "analysis1_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="chartofaccountDIT.Analysis1",
                    ),
                ),
                (
                    "analysis2_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="chartofaccountDIT.Analysis2",
                    ),
                ),
                (
                    "cost_centre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="costcentre.CostCentre",
                    ),
                ),
                (
                    "financial_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="forecast.FinancialPeriod",
                    ),
                ),
                (
                    "financial_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="forecast.FinancialYear",
                    ),
                ),
                (
                    "natural_account_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="chartofaccountDIT.NaturalCode",
                    ),
                ),
                (
                    "programme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="chartofaccountDIT.ProgrammeCode",
                    ),
                ),
                (
                    "project_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="chartofaccountDIT.ProjectCode",
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(name="adireport", unique_together=set()),
        migrations.AddField(
            model_name="budget",
            name="financial_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="forecast.FinancialYear"
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="natural_account_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="chartofaccountDIT.NaturalCode",
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="programme",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="chartofaccountDIT.ProgrammeCode",
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="project_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="chartofaccountDIT.ProjectCode",
            ),
        ),
        migrations.RemoveField(model_name="adireport", name="active"),
        migrations.RemoveField(model_name="adireport", name="created"),
        migrations.RemoveField(model_name="adireport", name="financial_year"),
        migrations.RemoveField(model_name="adireport", name="updated"),
        migrations.AlterUniqueTogether(
            name="monthlyfigure",
            unique_together={
                (
                    "programme",
                    "cost_centre",
                    "natural_account_code",
                    "analysis1_code",
                    "analysis2_code",
                    "project_code",
                    "financial_year",
                    "financial_period",
                )
            },
        ),
        migrations.AlterUniqueTogether(
            name="budget",
            unique_together={
                (
                    "programme",
                    "cost_centre",
                    "natural_account_code",
                    "analysis1_code",
                    "analysis2_code",
                    "project_code",
                    "financial_year",
                )
            },
        ),
    ]
