# Generated by Django 2.2.13 on 2020-08-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0003_auto_20200615_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecasteditstate',
            name='closed',
            field=models.BooleanField(default=False, help_text='Ticking this option will close editing access to all non finance staff. Forecast editing is still available to Finance business partners/BSCEs and admin.'),
        ),
        migrations.AlterField(
            model_name='forecasteditstate',
            name='lock_date',
            field=models.DateField(blank=True, help_text="The system is locked from the date entered. The system will remain locked to users without 'unlocked' user status, until the date is removed from the input field above. Please remember to archive the data after locking the forecast.", null=True, verbose_name='Lock system'),
        ),
        migrations.AlterField(
            model_name='simplehistoryforecasteditstate',
            name='closed',
            field=models.BooleanField(default=False, help_text='Ticking this option will close editing access to all non finance staff. Forecast editing is still available to Finance business partners/BSCEs and admin.'),
        ),
        migrations.AlterField(
            model_name='simplehistoryforecasteditstate',
            name='lock_date',
            field=models.DateField(blank=True, help_text="The system is locked from the date entered. The system will remain locked to users without 'unlocked' user status, until the date is removed from the input field above. Please remember to archive the data after locking the forecast.", null=True, verbose_name='Lock system'),
        ),
    ]
