# Generated by Django 2.2.10 on 2020-04-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0006_auto_20200402_1703'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='actualuploadmonthlyfigure',
            constraint=models.UniqueConstraint(condition=models.Q(archived_status__isnull=False), fields=('financial_code', 'financial_year', 'financial_period', 'archived_status'), name='actualuploadmonthlyfigure_unique1'),
        ),
        migrations.AddConstraint(
            model_name='actualuploadmonthlyfigure',
            constraint=models.UniqueConstraint(condition=models.Q(archived_status__isnull=True), fields=('financial_code', 'financial_year', 'financial_period'), name='actualuploadmonthlyfigure_unique2'),
        ),
        migrations.AddConstraint(
            model_name='budgetmonthlyfigure',
            constraint=models.UniqueConstraint(condition=models.Q(archived_status__isnull=False), fields=('financial_code', 'financial_year', 'financial_period', 'archived_status'), name='budgetmonthlyfigure_unique1'),
        ),
        migrations.AddConstraint(
            model_name='budgetmonthlyfigure',
            constraint=models.UniqueConstraint(condition=models.Q(archived_status__isnull=True), fields=('financial_code', 'financial_year', 'financial_period'), name='budgetmonthlyfigure_unique2'),
        ),
        migrations.AddConstraint(
            model_name='budgetuploadmonthlyfigure',
            constraint=models.UniqueConstraint(condition=models.Q(archived_status__isnull=False), fields=('financial_code', 'financial_year', 'financial_period', 'archived_status'), name='budgetuploadmonthlyfigure_unique1'),
        ),
        migrations.AddConstraint(
            model_name='budgetuploadmonthlyfigure',
            constraint=models.UniqueConstraint(condition=models.Q(archived_status__isnull=True), fields=('financial_code', 'financial_year', 'financial_period'), name='budgetuploadmonthlyfigure_unique2'),
        ),
        migrations.AddConstraint(
            model_name='forecastmonthlyfigure',
            constraint=models.UniqueConstraint(condition=models.Q(archived_status__isnull=False), fields=('financial_code', 'financial_year', 'financial_period', 'archived_status'), name='forecastmonthlyfigure_unique1'),
        ),
        migrations.AddConstraint(
            model_name='forecastmonthlyfigure',
            constraint=models.UniqueConstraint(condition=models.Q(archived_status__isnull=True), fields=('financial_code', 'financial_year', 'financial_period'), name='forecastmonthlyfigure_unique2'),
        ),
    ]
