# Generated by Django 2.2.10 on 2020-04-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0007_auto_20200402_1711'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='actualuploadmonthlyfigure',
            name='actualuploadmonthlyfigure_unique1',
        ),
        migrations.RemoveConstraint(
            model_name='actualuploadmonthlyfigure',
            name='actualuploadmonthlyfigure_unique2',
        ),
        migrations.RemoveConstraint(
            model_name='budgetmonthlyfigure',
            name='budgetmonthlyfigure_unique1',
        ),
        migrations.RemoveConstraint(
            model_name='budgetmonthlyfigure',
            name='budgetmonthlyfigure_unique2',
        ),
        migrations.RemoveConstraint(
            model_name='budgetuploadmonthlyfigure',
            name='budgetuploadmonthlyfigure_unique1',
        ),
        migrations.RemoveConstraint(
            model_name='budgetuploadmonthlyfigure',
            name='budgetuploadmonthlyfigure_unique2',
        ),
        migrations.RemoveConstraint(
            model_name='forecastmonthlyfigure',
            name='forecastmonthlyfigure_unique1',
        ),
        migrations.RemoveConstraint(
            model_name='forecastmonthlyfigure',
            name='forecastmonthlyfigure_unique2',
        ),
        migrations.RemoveField(
            model_name='actualuploadmonthlyfigure',
            name='archived_status',
        ),
        migrations.RemoveField(
            model_name='budgetuploadmonthlyfigure',
            name='archived_status',
        ),
        migrations.RemoveField(
            model_name='simplehistoryactualuploadmonthlyfigure',
            name='archived_status',
        ),
        migrations.RemoveField(
            model_name='simplehistorybudgetuploadmonthlyfigure',
            name='archived_status',
        ),
        migrations.AddConstraint(
            model_name='actualuploadmonthlyfigure',
            constraint=models.UniqueConstraint(fields=('financial_code', 'financial_year', 'financial_period'), name='ActualUploadMonthlyFigure_unique1'),
        ),
        migrations.AddConstraint(
            model_name='budgetmonthlyfigure',
            constraint=models.UniqueConstraint(condition=models.Q(archived_status__isnull=False), fields=('financial_code', 'financial_year', 'financial_period', 'archived_status'), name='BudgetMonthlyFigure_unique1'),
        ),
        migrations.AddConstraint(
            model_name='budgetmonthlyfigure',
            constraint=models.UniqueConstraint(condition=models.Q(archived_status__isnull=True), fields=('financial_code', 'financial_year', 'financial_period'), name='BudgetMonthlyFigure_unique2'),
        ),
        migrations.AddConstraint(
            model_name='budgetuploadmonthlyfigure',
            constraint=models.UniqueConstraint(fields=('financial_code', 'financial_year', 'financial_period'), name='BudgetUploadMonthlyFigure_unique1'),
        ),
        migrations.AddConstraint(
            model_name='forecastmonthlyfigure',
            constraint=models.UniqueConstraint(condition=models.Q(archived_status__isnull=False), fields=('financial_code', 'financial_year', 'financial_period', 'archived_status'), name='ForecastMonthlyFigure_unique1'),
        ),
        migrations.AddConstraint(
            model_name='forecastmonthlyfigure',
            constraint=models.UniqueConstraint(condition=models.Q(archived_status__isnull=True), fields=('financial_code', 'financial_year', 'financial_period'), name='ForecastMonthlyFigure_unique2'),
        ),
    ]
