# Generated by Django 2.2.10 on 2020-05-06 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0008_auto_20200408_0815'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialcode',
            options={'permissions': [('can_view_forecasts', 'Can view forecast'), ('can_upload_files', 'Can upload files'), ('can_download_oscar', 'Can download OSCAR'), ('can_download_mi_reports', 'Can download mi reports')]},
        ),
    ]
