# Generated by Django 2.2 on 2019-07-08 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0008_auto_20190227_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.FinancialYear'),
        ),
        migrations.AlterField(
            model_name='monthlyfigure',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.FinancialYear'),
        ),
        migrations.DeleteModel(
            name='FinancialYear',
        ),
    ]
