# Generated by Django 2.2.4 on 2019-09-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("forecast", "0014_delete_subsegmentuktimapping")]

    operations = [
        migrations.RunSQL('DROP VIEW "forecast_oscarreturn";'),
        migrations.DeleteModel(name="ADIReport"),
        migrations.AlterField(
            model_name="budget", name="budget", field=models.BigIntegerField(default=0)
        ),
        migrations.AlterField(
            model_name="monthlyfigure",
            name="amount",
            field=models.BigIntegerField(default=0),
        ),
    ]
