# Generated by Django 2.2.4 on 2019-10-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("forecast", "0016_recreate_oscar_view")]

    operations = [
        migrations.AddField(
            model_name="financialperiod",
            name="display_figure",
            field=models.BooleanField(default=True),
        )
    ]
