# Generated by Django 2.2.4 on 2019-10-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0017_financialperiod_display_figure'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastExpenditureType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_expenditure_type_name', models.CharField(max_length=100)),
                ('forecast_expenditure_type_description', models.CharField(max_length=100)),
                ('forecast_expenditure_type_display_order', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='budget',
            name='expenditure_type_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='expenditure_type_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='budget',
            name='expenditure_type_short_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='monthlyfigure',
            name='expenditure_type_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='monthlyfigure',
            name='expenditure_type_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlyfigure',
            name='expenditure_type_short_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
