# Generated by Django 2.2.4 on 2019-10-11 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0020_auto_20191011_1751'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalcForecastExpenditureType',
        ),
    ]
