# Generated by Django 2.2.4 on 2019-10-23 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccountDIT', '0049_auto_20191003_1317'),
        ('forecast', '0020_auto_20191014_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastexpendituretype',
            name='programme_budget_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chartofaccountDIT.BudgetType'),
        ),
        migrations.AlterUniqueTogether(
            name='forecastexpendituretype',
            unique_together={('nac_economic_budget_code', 'programme_budget_type')},
        ),
    ]
