# Generated by Django 2.2.4 on 2019-10-11 18:11

from django.db import migrations


def create_forecast_expenditure_types(apps, schema_editor):
    ForecastExpenditureType = apps.get_model("forecast", "ForecastExpenditureType")
    BudgetType = apps.get_model("chartofaccountDIT", "BudgetType")

    del_type = BudgetType.objects.get(budget_type_key="DEL")
    ame_type = BudgetType.objects.get(budget_type_key="AME")
    admin_type = BudgetType.objects.get(budget_type_key="ADMIN")

    ForecastExpenditureType.objects.create(
        forecast_expenditure_type_name="Capital",
        forecast_expenditure_type_description="Capital",
        forecast_expenditure_type_display_order=3,
        nac_economic_budget_code="CAPITAL",
        programme_budget_type=del_type,
    ).save()

    ForecastExpenditureType.objects.create(
        forecast_expenditure_type_name="Capital",
        forecast_expenditure_type_description="Capital",
        forecast_expenditure_type_display_order=3,
        nac_economic_budget_code="CAPITAL",
        programme_budget_type=ame_type,
    ).save()

    ForecastExpenditureType.objects.create(
        forecast_expenditure_type_name="Capital",
        forecast_expenditure_type_description="Capital",
        forecast_expenditure_type_display_order=3,
        nac_economic_budget_code="CAPITAL",
        programme_budget_type=admin_type,
    ).save()

    ForecastExpenditureType.objects.create(
        nac_economic_budget_code="RESOURCE",
        programme_budget_type=del_type,
        forecast_expenditure_type_name='Programme',
        forecast_expenditure_type_description='Programme Resource',
        forecast_expenditure_type_display_order=2
    ).save()

    ForecastExpenditureType.objects.create(
        nac_economic_budget_code="RESOURCE",
        programme_budget_type=ame_type,
        forecast_expenditure_type_name='Programme',
        forecast_expenditure_type_description='Programme Resource',
        forecast_expenditure_type_display_order=2
    ).save()

    ForecastExpenditureType.objects.create(
        nac_economic_budget_code="RESOURCE",
        programme_budget_type=admin_type,
        forecast_expenditure_type_name='Admin',
        forecast_expenditure_type_description='Admin Resource',
        forecast_expenditure_type_display_order=1
    ).save()


class Migration(migrations.Migration):
    dependencies = [("forecast", "0021_auto_20191023_1509")]

    operations = [migrations.RunPython(create_forecast_expenditure_types)]
