# Generated by Django 2.2.4 on 2019-10-11 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccountDIT', '0049_auto_20191003_1317'),
        ('forecast', '0021_delete_calcforecastexpendituretype'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalcForecastExpenditureType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nac_economic_budget_code', models.CharField(max_length=255, verbose_name='economic budget code')),
                ('forecast_expenditure_type_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecast.ForecastExpenditureType')),
                ('programme_budget_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chartofaccountDIT.BudgetType')),
            ],
        ),
    ]
