# Generated by Django 2.2.4 on 2019-10-29 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0022_data_20191011_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='forecast_expenditure_type',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='forecast.ForecastExpenditureType'),
        ),
        migrations.AlterField(
            model_name='monthlyfigure',
            name='forecast_expenditure_type',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='forecast.ForecastExpenditureType'),
        ),
    ]
