# Generated by Django 2.2.4 on 2019-11-05 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0023_fileupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileUpload',
        ),
    ]
