# Generated by Django 2.2.4 on 2019-11-05 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0023_auto_20191029_1136'),
        ('forecast', '0024_delete_fileupload'),
    ]

    operations = [
    ]
