# Generated by Django 2.2.4 on 2019-11-12 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costcentre', '0029_auto_20190703_0751'),
        ('core', '0013_delete_admininfo'),
        ('chartofaccountDIT', '0051_auto_20191106_1235'),
        ('forecast', '0025_merge_20191105_1621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oscarreturn',
            options={},
        ),
        migrations.CreateModel(
            name='UploadingActuals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(default=0)),
                ('analysis1_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chartofaccountDIT.Analysis1')),
                ('analysis2_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chartofaccountDIT.Analysis2')),
                ('cost_centre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='costcentre.CostCentre')),
                ('financial_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forecast.FinancialPeriod')),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.FinancialYear')),
                ('forecast_expenditure_type', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='forecast.ForecastExpenditureType')),
                ('natural_account_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chartofaccountDIT.NaturalCode')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chartofaccountDIT.ProgrammeCode')),
                ('project_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chartofaccountDIT.ProjectCode')),
            ],
            options={
                'unique_together': {('programme', 'cost_centre', 'natural_account_code', 'analysis1_code', 'analysis2_code', 'project_code', 'financial_year', 'financial_period')},
            },
        ),
    ]
