# Generated by Django 2.2.4 on 2019-11-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0026_auto_20191112_0924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oscarreturn',
            options={'managed': False, 'ordering': ['sub_segment_code']},
        ),
        migrations.AddField(
            model_name='uploadingactuals',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
