# Generated by Django 2.2.4 on 2019-11-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0027_auto_20191112_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadingactuals',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Row ID'),
        ),
    ]
