# Generated by Django 2.2.4 on 2019-11-18 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_delete_admininfo'),
        ('costcentre', '0029_auto_20190703_0751'),
        ('chartofaccountDIT', '0051_auto_20191106_1235'),
        ('forecast', '0029_forecastpermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartOfAccountFullCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis1_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chartofaccountDIT.Analysis1')),
                ('analysis2_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chartofaccountDIT.Analysis2')),
                ('cost_centre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='costcentre.CostCentre')),
                ('forecast_expenditure_type', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='forecast.ForecastExpenditureType')),
                ('natural_account_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chartofaccountDIT.NaturalCode')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chartofaccountDIT.ProgrammeCode')),
                ('project_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chartofaccountDIT.ProjectCode')),
            ],
        ),
        migrations.CreateModel(
            name='ForecastActualBudgetFigure',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Monthly ID')),
                ('amount', models.BigIntegerField(default=0)),
                ('chart_of_account_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forecast.ChartOfAccountFullCode')),
                ('financial_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forecast.FinancialPeriod')),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.FinancialYear')),
            ],
            options={
                'unique_together': {('chart_of_account_code', 'financial_year', 'financial_period')},
            },
        ),
    ]
