# Generated by Django 2.2.4 on 2019-12-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0029_forecastpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyfigure',
            name='version',
            field=models.IntegerField(),
        ),
    ]
