# Generated by Django 2.2.4 on 2019-11-20 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0029_forecastpermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadingBudgets',
            fields=[
                ('uploadingactuals_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='forecast.ActualsTemporaryStore')),
            ],
            options={
                'abstract': False,
            },
            bases=('forecast.uploadingactuals',),
        ),
    ]
