# Generated by Django 2.2.4 on 2019-11-25 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0030_uploadingbudgets'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadingBudgets',
        ),
    ]
