# Generated by Django 2.2.4 on 2019-11-18 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_delete_admininfo'),
        ('forecast', '0030_chartofaccountfullcode_forecastactualbudgetfigure'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadingactuals',
            name='chart_of_account_code',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='forecast.ChartOfAccountFullCode'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='forecastactualbudgetfigure',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='monthlyfigure',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlyfigure',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='uploadingactuals',
            unique_together={('chart_of_account_code', 'financial_year', 'financial_period')},
        ),
        migrations.DeleteModel(
            name='Budget',
        ),
        migrations.RemoveField(
            model_name='monthlyfigure',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='monthlyfigure',
            name='analysis1_code',
        ),
        migrations.RemoveField(
            model_name='monthlyfigure',
            name='analysis2_code',
        ),
        migrations.RemoveField(
            model_name='monthlyfigure',
            name='cost_centre',
        ),
        migrations.RemoveField(
            model_name='monthlyfigure',
            name='financial_period',
        ),
        migrations.RemoveField(
            model_name='monthlyfigure',
            name='financial_year',
        ),
        migrations.RemoveField(
            model_name='monthlyfigure',
            name='forecast_expenditure_type',
        ),
        migrations.RemoveField(
            model_name='monthlyfigure',
            name='natural_account_code',
        ),
        migrations.RemoveField(
            model_name='monthlyfigure',
            name='programme',
        ),
        migrations.RemoveField(
            model_name='monthlyfigure',
            name='project_code',
        ),
        migrations.RemoveField(
            model_name='uploadingactuals',
            name='active',
        ),
        migrations.RemoveField(
            model_name='uploadingactuals',
            name='analysis1_code',
        ),
        migrations.RemoveField(
            model_name='uploadingactuals',
            name='analysis2_code',
        ),
        migrations.RemoveField(
            model_name='uploadingactuals',
            name='cost_centre',
        ),
        migrations.RemoveField(
            model_name='uploadingactuals',
            name='forecast_expenditure_type',
        ),
        migrations.RemoveField(
            model_name='uploadingactuals',
            name='natural_account_code',
        ),
        migrations.RemoveField(
            model_name='uploadingactuals',
            name='programme',
        ),
        migrations.RemoveField(
            model_name='uploadingactuals',
            name='project_code',
        ),
    ]
