# Generated by Django 2.2.4 on 2019-12-05 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccountDIT', '0051_auto_20191106_1235'),
        ('costcentre', '0029_auto_20190703_0751'),
        ('core', '0013_delete_admininfo'),
        ('forecast', '0030_monthlyfigure_version'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monthlyfigure',
            unique_together={('programme', 'cost_centre', 'natural_account_code', 'analysis1_code', 'analysis2_code', 'project_code', 'financial_year', 'financial_period', 'version')},
        ),
    ]
