# Generated by Django 2.2.4 on 2019-12-10 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_delete_admininfo'),
        ('chartofaccountDIT', '0051_auto_20191106_1235'),
        ('costcentre', '0029_auto_20190703_0751'),
        ('forecast', '0031_auto_20191205_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualsTemporaryStore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Row ID')),
                ('amount', models.BigIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BudgetsTemporaryStore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Row ID')),
                ('amount', models.BigIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FinancialCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis1_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chartofaccountDIT.Analysis1')),
                ('analysis2_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chartofaccountDIT.Analysis2')),
                ('cost_centre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='costcentre.CostCentre')),
                ('forecast_expenditure_type', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='forecast.ForecastExpenditureType')),
                ('natural_account_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chartofaccountDIT.NaturalCode')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chartofaccountDIT.ProgrammeCode')),
                ('project_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chartofaccountDIT.ProjectCode')),
            ],
            options={
                'unique_together': {('programme', 'cost_centre', 'natural_account_code', 'analysis1_code', 'analysis2_code', 'project_code')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyFigureAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('amount', models.BigIntegerField(default=0)),
                ('version', models.IntegerField(default=1)),
                ('monthly_figure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_figure_amounts', to='forecast.MonthlyFigure')),
            ],
            options={
                'unique_together': {('monthly_figure', 'version')},
            },
        ),
        migrations.RenameField(
            model_name='budget',
            old_name='budget',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='budget',
            name='financial_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forecast.FinancialPeriod'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UploadingActuals',
        ),
        migrations.AddField(
            model_name='budgetstemporarystore',
            name='financial_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forecast.FinancialCode'),
        ),
        migrations.AddField(
            model_name='budgetstemporarystore',
            name='financial_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forecast.FinancialPeriod'),
        ),
        migrations.AddField(
            model_name='budgetstemporarystore',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.FinancialYear'),
        ),
        migrations.AddField(
            model_name='actualstemporarystore',
            name='financial_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forecast.FinancialCode'),
        ),
        migrations.AddField(
            model_name='actualstemporarystore',
            name='financial_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forecast.FinancialPeriod'),
        ),
        migrations.AddField(
            model_name='actualstemporarystore',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.FinancialYear'),
        ),
        migrations.AddField(
            model_name='budget',
            name='financial_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_financial_code', to='forecast.FinancialCode'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlyfigure',
            name='financial_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_figures', to='forecast.FinancialCode'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('financial_code', 'financial_year', 'financial_period')},
        ),
        migrations.AlterUniqueTogether(
            name='monthlyfigure',
            unique_together={('financial_code', 'financial_year', 'financial_period')},
        ),
        migrations.AlterUniqueTogether(
            name='budgetstemporarystore',
            unique_together={('financial_code', 'financial_year', 'financial_period')},
        ),
        migrations.AlterUniqueTogether(
            name='actualstemporarystore',
            unique_together={('financial_code', 'financial_year', 'financial_period')},
        ),
        migrations.RemoveField(
            model_name='budget',
            name='analysis1_code',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='analysis2_code',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='cost_centre',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='forecast_expenditure_type',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='natural_account_code',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='programme',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='project_code',
        ),
        migrations.RemoveField(
            model_name='monthlyfigure',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='monthlyfigure',
            name='analysis1_code',
        ),
        migrations.RemoveField(
            model_name='monthlyfigure',
            name='analysis2_code',
        ),
        migrations.RemoveField(
            model_name='monthlyfigure',
            name='cost_centre',
        ),
        migrations.RemoveField(
            model_name='monthlyfigure',
            name='forecast_expenditure_type',
        ),
        migrations.RemoveField(
            model_name='monthlyfigure',
            name='natural_account_code',
        ),
        migrations.RemoveField(
            model_name='monthlyfigure',
            name='programme',
        ),
        migrations.RemoveField(
            model_name='monthlyfigure',
            name='project_code',
        ),
        migrations.RemoveField(
            model_name='monthlyfigure',
            name='version',
        ),
    ]
