# Generated by Django 2.2.4 on 2019-11-18 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0031_auto_20191118_1654'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonthlyFigure',
        ),
    ]
