# Generated by Django 2.2.4 on 2019-12-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0031_auto_20191205_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyfigure',
            name='current',
            field=models.IntegerField(),
        ),
    ]
