# Generated by Django 2.2.4 on 2019-11-25 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0032_uploadingbudgets'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='financial_period',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='forecast.FinancialPeriod'),
            preserve_default=False,
        ),
    ]
