# Generated by Django 2.2.4 on 2019-12-11 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0032_auto_20191210_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('amount', models.BigIntegerField(default=0)),
                ('version', models.IntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='budget',
            name='financial_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='forecast.FinancialCode'),
        ),
        migrations.DeleteModel(
            name='ActualsTemporaryStore',
        ),
        migrations.AddField(
            model_name='budgetamount',
            name='budget_figure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_amounts', to='forecast.Budget'),
        ),
        migrations.AlterUniqueTogether(
            name='budgetamount',
            unique_together={('budget_figure', 'version')},
        ),
    ]
