# Generated by Django 2.2.4 on 2019-12-11 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0033_auto_20191211_0847'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BudgetsTemporaryStore',
        ),
    ]
