# Generated by Django 2.2.4 on 2019-11-27 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costcentre', '0029_auto_20190703_0751'),
        ('core', '0013_delete_admininfo'),
        ('chartofaccountDIT', '0051_auto_20191106_1235'),
        ('forecast', '0033_budget_financial_period'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('programme', 'cost_centre', 'natural_account_code', 'analysis1_code', 'analysis2_code', 'project_code', 'financial_year', 'financial_period')},
        ),
    ]
