# Generated by Django 2.2.4 on 2019-11-28 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costcentre', '0029_auto_20190703_0751'),
        ('core', '0013_delete_admininfo'),
        ('chartofaccountDIT', '0051_auto_20191106_1235'),
        ('forecast', '0034_auto_20191127_0941'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadingBudgets',
            new_name='ActualsTemporaryStore',
        ),
        migrations.RenameModel(
            old_name='UploadingActuals',
            new_name='BudgetsTemporaryStore',
        ),
    ]
