# Generated by Django 2.2.4 on 2019-12-31 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0035_auto_20191220_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyfigure',
            name='financial_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_periods', to='forecast.FinancialPeriod'),
        ),
    ]
