# Generated by Django 2.2.4 on 2019-12-09 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costcentre', '0029_auto_20190703_0751'),
        ('core', '0013_delete_admininfo'),
        ('chartofaccountDIT', '0051_auto_20191106_1235'),
        ('forecast', '0036_auto_20191128_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyfigure',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='FinancialCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis1_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chartofaccountDIT.Analysis1')),
                ('analysis2_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chartofaccountDIT.Analysis2')),
                ('cost_centre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='costcentre.CostCentre')),
                ('forecast_expenditure_type', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='forecast.ForecastExpenditureType')),
                ('natural_account_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chartofaccountDIT.NaturalCode')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chartofaccountDIT.ProgrammeCode')),
                ('project_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chartofaccountDIT.ProjectCode')),
            ],
            options={
                'unique_together': {('programme', 'cost_centre', 'natural_account_code', 'analysis1_code', 'analysis2_code', 'project_code')},
            },
        ),
        migrations.AddField(
            model_name='actualstemporarystore',
            name='financial_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forecast.FinancialCode'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budget',
            name='financial_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_financial_code', to='forecast.FinancialCode'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budgetstemporarystore',
            name='financial_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forecast.FinancialCode'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlyfigure',
            name='financial_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_figures', to='forecast.FinancialCode'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='actualstemporarystore',
            unique_together={('financial_code', 'financial_year', 'financial_period')},
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('financial_code', 'financial_year', 'financial_period')},
        ),
        migrations.AlterUniqueTogether(
            name='budgetstemporarystore',
            unique_together={('financial_code', 'financial_year', 'financial_period')},
        ),
        migrations.AlterUniqueTogether(
            name='monthlyfigure',
            unique_together={('financial_code', 'financial_year', 'financial_period', 'version')},
        ),
        migrations.RemoveField(
            model_name='actualstemporarystore',
            name='analysis1_code',
        ),
        migrations.RemoveField(
            model_name='actualstemporarystore',
            name='analysis2_code',
        ),
        migrations.RemoveField(
            model_name='actualstemporarystore',
            name='cost_centre',
        ),
        migrations.RemoveField(
            model_name='actualstemporarystore',
            name='forecast_expenditure_type',
        ),
        migrations.RemoveField(
            model_name='actualstemporarystore',
            name='natural_account_code',
        ),
        migrations.RemoveField(
            model_name='actualstemporarystore',
            name='programme',
        ),
        migrations.RemoveField(
            model_name='actualstemporarystore',
            name='project_code',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='analysis1_code',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='analysis2_code',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='cost_centre',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='forecast_expenditure_type',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='natural_account_code',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='programme',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='project_code',
        ),
        migrations.RemoveField(
            model_name='budgetstemporarystore',
            name='analysis1_code',
        ),
        migrations.RemoveField(
            model_name='budgetstemporarystore',
            name='analysis2_code',
        ),
        migrations.RemoveField(
            model_name='budgetstemporarystore',
            name='cost_centre',
        ),
        migrations.RemoveField(
            model_name='budgetstemporarystore',
            name='forecast_expenditure_type',
        ),
        migrations.RemoveField(
            model_name='budgetstemporarystore',
            name='natural_account_code',
        ),
        migrations.RemoveField(
            model_name='budgetstemporarystore',
            name='programme',
        ),
        migrations.RemoveField(
            model_name='budgetstemporarystore',
            name='project_code',
        ),
        migrations.RemoveField(
            model_name='monthlyfigure',
            name='analysis1_code',
        ),
        migrations.RemoveField(
            model_name='monthlyfigure',
            name='analysis2_code',
        ),
        migrations.RemoveField(
            model_name='monthlyfigure',
            name='cost_centre',
        ),
        migrations.RemoveField(
            model_name='monthlyfigure',
            name='forecast_expenditure_type',
        ),
        migrations.RemoveField(
            model_name='monthlyfigure',
            name='natural_account_code',
        ),
        migrations.RemoveField(
            model_name='monthlyfigure',
            name='programme',
        ),
        migrations.RemoveField(
            model_name='monthlyfigure',
            name='project_code',
        ),
    ]
