# Generated by Django 2.2.8 on 2020-01-13 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_historicalgroup_historicalpermission_historicaluser'),
        ('forecast', '0038_auto_create_view_forecast_oscar_return'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMonthlyFigures',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('amount', models.BigIntegerField(default=0)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_actual', models.BooleanField(default=False)),
                ('version', models.IntegerField()),
                ('financial_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecast_historicalmonthlyfigures_related', to='forecast.FinancialCode')),
                ('financial_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecast_historicalmonthlyfigures_related', to='forecast.FinancialPeriod')),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.FinancialYear')),
            ],
            options={
                'abstract': False,
                'unique_together': {('financial_code', 'financial_year', 'financial_period')},
            },
        ),
        migrations.RemoveField(
            model_name='historicalmonthlyfigure',
            name='financial_code',
        ),
        migrations.RemoveField(
            model_name='historicalmonthlyfigure',
            name='financial_period',
        ),
        migrations.RemoveField(
            model_name='historicalmonthlyfigure',
            name='financial_year',
        ),
        migrations.RemoveField(
            model_name='historicalmonthlyfigure',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalmonthlyfigureamount',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalmonthlyfigureamount',
            name='monthly_figure',
        ),
        migrations.AlterUniqueTogether(
            name='monthlyfigureamount',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='monthlyfigureamount',
            name='monthly_figure',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='active',
        ),
        migrations.RemoveField(
            model_name='monthlyfigure',
            name='active',
        ),
        migrations.AddField(
            model_name='budget',
            name='starting_amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlyfigure',
            name='amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlyfigure',
            name='starting_amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='budget',
            name='financial_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecast_budget_related', to='forecast.FinancialCode'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='financial_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecast_budget_related', to='forecast.FinancialPeriod'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='monthlyfigure',
            name='financial_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecast_monthlyfigure_related', to='forecast.FinancialCode'),
        ),
        migrations.AlterField(
            model_name='monthlyfigure',
            name='financial_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecast_monthlyfigure_related', to='forecast.FinancialPeriod'),
        ),
        migrations.AlterField(
            model_name='monthlyfigure',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='BudgetAmount',
        ),
        migrations.DeleteModel(
            name='HistoricalMonthlyFigure',
        ),
        migrations.DeleteModel(
            name='HistoricalMonthlyFigureAmount',
        ),
        migrations.DeleteModel(
            name='MonthlyFigureAmount',
        ),
    ]
