# Generated by Django 2.2.8 on 2020-01-13 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0014_historicalgroup_historicalpermission_historicaluser'),
        ('forecast', '0042_temporarybudget'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualUploadMonthlyFigure',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('amount', models.BigIntegerField(default=0)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('financial_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecast_actualuploadmonthlyfigure_related', to='forecast.FinancialCode')),
                ('financial_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecast_actualuploadmonthlyfigure_related', to='forecast.FinancialPeriod')),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.FinancialYear')),
            ],
            options={
                'abstract': False,
                'unique_together': {('financial_code', 'financial_year', 'financial_period')},
            },
        ),
        migrations.CreateModel(
            name='BudgetMonthlyFigure',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('amount', models.BigIntegerField(default=0)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('starting_amount', models.BigIntegerField(default=0)),
                ('financial_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecast_budgetmonthlyfigure_related', to='forecast.FinancialCode')),
                ('financial_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecast_budgetmonthlyfigure_related', to='forecast.FinancialPeriod')),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.FinancialYear')),
            ],
            options={
                'abstract': False,
                'unique_together': {('financial_code', 'financial_year', 'financial_period')},
            },
        ),
        migrations.CreateModel(
            name='BudgetUploadMonthlyFigure',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('amount', models.BigIntegerField(default=0)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('financial_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecast_budgetuploadmonthlyfigure_related', to='forecast.FinancialCode')),
                ('financial_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecast_budgetuploadmonthlyfigure_related', to='forecast.FinancialPeriod')),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.FinancialYear')),
            ],
            options={
                'abstract': False,
                'unique_together': {('financial_code', 'financial_year', 'financial_period')},
            },
        ),
        migrations.CreateModel(
            name='ForecastMonthlyFigure',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('amount', models.BigIntegerField(default=0)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('starting_amount', models.BigIntegerField(default=0)),
                ('financial_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecast_forecastmonthlyfigure_related', to='forecast.FinancialCode')),
                ('financial_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecast_forecastmonthlyfigure_related', to='forecast.FinancialPeriod')),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.FinancialYear')),
            ],
            options={
                'abstract': False,
                'unique_together': {('financial_code', 'financial_year', 'financial_period')},
            },
        ),
        migrations.CreateModel(
            name='HistoricalForecastMonthlyFigure',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('amount', models.BigIntegerField(default=0)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_actual', models.BooleanField(default=False)),
                ('financial_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecast_historicalforecastmonthlyfigure_related', to='forecast.FinancialCode')),
                ('financial_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecast_historicalforecastmonthlyfigure_related', to='forecast.FinancialPeriod')),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.FinancialYear')),
                ('forecast_month', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historical_forecast_monthly_figures', to='forecast.FinancialPeriod')),
                ('forecast_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historical_forecast_monthly_figures', to='core.FinancialYear')),
            ],
            options={
                'abstract': False,
                'unique_together': {('financial_code', 'financial_year', 'financial_period')},
            },
        ),
        migrations.RenameModel(
            old_name='HistoricalBudget',
            new_name='HistoricalBudgetMonthlyFigure',
        ),
        migrations.RemoveField(
            model_name='historicalmonthlyfigure',
            name='financial_code',
        ),
        migrations.RemoveField(
            model_name='historicalmonthlyfigure',
            name='financial_period',
        ),
        migrations.RemoveField(
            model_name='historicalmonthlyfigure',
            name='financial_year',
        ),
        migrations.RemoveField(
            model_name='historicalmonthlyfigure',
            name='history_user',
        ),
        migrations.AlterUniqueTogether(
            name='historicalmonthlyfigures',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='historicalmonthlyfigures',
            name='financial_code',
        ),
        migrations.RemoveField(
            model_name='historicalmonthlyfigures',
            name='financial_period',
        ),
        migrations.RemoveField(
            model_name='historicalmonthlyfigures',
            name='financial_year',
        ),
        migrations.AlterUniqueTogether(
            name='monthlyfigure',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='monthlyfigure',
            name='financial_code',
        ),
        migrations.RemoveField(
            model_name='monthlyfigure',
            name='financial_period',
        ),
        migrations.RemoveField(
            model_name='monthlyfigure',
            name='financial_year',
        ),
        migrations.AlterUniqueTogether(
            name='temporarybudget',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='temporarybudget',
            name='financial_code',
        ),
        migrations.RemoveField(
            model_name='temporarybudget',
            name='financial_period',
        ),
        migrations.RemoveField(
            model_name='temporarybudget',
            name='financial_year',
        ),
        migrations.AlterUniqueTogether(
            name='temporarymonthlyfigure',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='temporarymonthlyfigure',
            name='financial_code',
        ),
        migrations.RemoveField(
            model_name='temporarymonthlyfigure',
            name='financial_period',
        ),
        migrations.RemoveField(
            model_name='temporarymonthlyfigure',
            name='financial_year',
        ),
        migrations.AlterModelOptions(
            name='historicalbudgetmonthlyfigure',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical budget monthly figure'},
        ),
        migrations.DeleteModel(
            name='Budget',
        ),
        migrations.DeleteModel(
            name='HistoricalMonthlyFigure',
        ),
        migrations.DeleteModel(
            name='HistoricalMonthlyFigures',
        ),
        migrations.DeleteModel(
            name='MonthlyFigure',
        ),
        migrations.DeleteModel(
            name='TemporaryBudget',
        ),
        migrations.DeleteModel(
            name='TemporaryMonthlyFigure',
        ),
    ]
