# Generated by Django 2.2.8 on 2020-01-13 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_historicalgroup_historicalpermission_historicaluser'),
        ('forecast', '0045_historicalforecastmonthlyfigure'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedForecastMonthlyFigure',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('amount', models.BigIntegerField(default=0)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_actual', models.BooleanField(default=False)),
                ('financial_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecast_archivedforecastmonthlyfigure_related', to='forecast.FinancialCode')),
                ('financial_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecast_archivedforecastmonthlyfigure_related', to='forecast.FinancialPeriod')),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.FinancialYear')),
                ('forecast_month', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historical_forecast_monthly_figures', to='forecast.FinancialPeriod')),
                ('forecast_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historical_forecast_monthly_figures', to='core.FinancialYear')),
            ],
            options={
                'abstract': False,
                'unique_together': {('financial_code', 'financial_year', 'financial_period')},
            },
        ),
        migrations.DeleteModel(
            name='PreviousForecastMonthlyFigure',
        ),
    ]
