# Generated by Django 2.2.8 on 2020-01-13 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0046_auto_20200113_1410'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='financialcode',
            unique_together=set(),
        ),
    ]
