# Generated by Django 2.2.8 on 2020-01-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0047_auto_20200113_1642'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='financialcode',
            constraint=models.UniqueConstraint(condition=models.Q(('analysis1_code__isnull', False), ('analysis2_code__isnull', False), ('project_code__isnull', False)), fields=('programme', 'cost_centre', 'natural_account_code', 'analysis1_code', 'analysis2_code', 'project_code'), name='financial_row_unique_6'),
        ),
        migrations.AddConstraint(
            model_name='financialcode',
            constraint=models.UniqueConstraint(condition=models.Q(('analysis1_code__isnull', True), ('analysis2_code__isnull', False), ('project_code__isnull', False)), fields=('programme', 'cost_centre', 'natural_account_code', 'analysis2_code', 'project_code'), name='financial_row_unique_5a'),
        ),
        migrations.AddConstraint(
            model_name='financialcode',
            constraint=models.UniqueConstraint(condition=models.Q(('analysis1_code__isnull', False), ('analysis2_code__isnull', True), ('project_code__isnull', False)), fields=('programme', 'cost_centre', 'natural_account_code', 'analysis1_code', 'project_code'), name='financial_row_unique_5b'),
        ),
        migrations.AddConstraint(
            model_name='financialcode',
            constraint=models.UniqueConstraint(condition=models.Q(('analysis1_code__isnull', False), ('analysis2_code__isnull', False), ('project_code__isnull', True)), fields=('programme', 'cost_centre', 'natural_account_code', 'analysis1_code', 'analysis2_code'), name='financial_row_unique_5c'),
        ),
        migrations.AddConstraint(
            model_name='financialcode',
            constraint=models.UniqueConstraint(condition=models.Q(('analysis1_code__isnull', True), ('analysis2_code__isnull', True), ('project_code__isnull', False)), fields=('programme', 'cost_centre', 'natural_account_code', 'project_code'), name='financial_row_unique_4a'),
        ),
        migrations.AddConstraint(
            model_name='financialcode',
            constraint=models.UniqueConstraint(condition=models.Q(('analysis1_code__isnull', False), ('analysis2_code__isnull', True), ('project_code__isnull', True)), fields=('programme', 'cost_centre', 'natural_account_code', 'analysis1_code'), name='financial_row_unique_4b'),
        ),
        migrations.AddConstraint(
            model_name='financialcode',
            constraint=models.UniqueConstraint(condition=models.Q(('analysis1_code__isnull', True), ('analysis2_code__isnull', False), ('project_code__isnull', True)), fields=('programme', 'cost_centre', 'natural_account_code', 'analysis2_code'), name='financial_row_unique_4c'),
        ),
        migrations.AddConstraint(
            model_name='financialcode',
            constraint=models.UniqueConstraint(condition=models.Q(('analysis1_code__isnull', True), ('analysis2_code__isnull', True), ('project_code__isnull', True)), fields=('programme', 'cost_centre', 'natural_account_code'), name='financial_row_unique_3'),
        ),
    ]
