# Generated by Django 2.2.8 on 2020-01-15 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0048_auto_20200113_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualuploadmonthlyfigure',
            name='financial_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecast_actualuploadmonthlyfigures', to='forecast.FinancialCode'),
        ),
        migrations.AlterField(
            model_name='actualuploadmonthlyfigure',
            name='financial_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecast_actualuploadmonthlyfigures', to='forecast.FinancialPeriod'),
        ),
        migrations.AlterField(
            model_name='archivedforecastmonthlyfigure',
            name='financial_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecast_archivedforecastmonthlyfigures', to='forecast.FinancialCode'),
        ),
        migrations.AlterField(
            model_name='archivedforecastmonthlyfigure',
            name='financial_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecast_archivedforecastmonthlyfigures', to='forecast.FinancialPeriod'),
        ),
        migrations.AlterField(
            model_name='budgetmonthlyfigure',
            name='financial_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecast_budgetmonthlyfigures', to='forecast.FinancialCode'),
        ),
        migrations.AlterField(
            model_name='budgetmonthlyfigure',
            name='financial_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecast_budgetmonthlyfigures', to='forecast.FinancialPeriod'),
        ),
        migrations.AlterField(
            model_name='budgetuploadmonthlyfigure',
            name='financial_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecast_budgetuploadmonthlyfigures', to='forecast.FinancialCode'),
        ),
        migrations.AlterField(
            model_name='budgetuploadmonthlyfigure',
            name='financial_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecast_budgetuploadmonthlyfigures', to='forecast.FinancialPeriod'),
        ),
        migrations.AlterField(
            model_name='forecastmonthlyfigure',
            name='financial_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecast_forecastmonthlyfigures', to='forecast.FinancialCode'),
        ),
        migrations.AlterField(
            model_name='forecastmonthlyfigure',
            name='financial_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecast_forecastmonthlyfigures', to='forecast.FinancialPeriod'),
        ),
    ]
