# Generated by Django 2.2.8 on 2020-01-16 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0049_auto_20200115_1303'),
    ]

    operations = [
        migrations.RunSQL("""UPDATE public."chartofaccountDIT_budgettype"
                                        SET budget_type_display_order=1
                                        WHERE budget_type_key = 'DEL';
                                    UPDATE public."chartofaccountDIT_budgettype"
                                        SET budget_type_display_order=1
                                        WHERE budget_type_key = 'ADMIN';
                                    UPDATE public."chartofaccountDIT_budgettype"
                                        SET budget_type_display_order=2
                                        WHERE budget_type_key = 'AME';
    	""")
    ]
