# Generated by Django 2.2.8 on 2020-01-23 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0056_historicalforecasteditlock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forecasteditlock',
            old_name='locked_for_editing',
            new_name='locked',
        ),
        migrations.RenameField(
            model_name='historicalforecasteditlock',
            old_name='locked_for_editing',
            new_name='locked',
        ),
    ]
