# Generated by Django 2.2.8 on 2020-01-23 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0057_auto_20200123_1148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forecasteditlock',
            options={'permissions': [('can_set_edit_lock', 'Can set edit lock'), ('can_edit_whilst_locked', 'Can edit forecasts whilst locked')]},
        ),
    ]
