# Generated by Django 2.2.8 on 2020-02-10 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0058_auto_20200123_1539'),
    ]

    operations = [

        migrations.RunSQL(

            """
            DROP VIEW if exists forecast_forecast_download_view ;

            CREATE VIEW public.forecast_forecast_download_view
            as
            SELECT coalesce(fc.id, f.financial_code_id) as financial_code_id,
                    financial_year,
                    coalesce(budget, 0) as budget,
                    coalesce(apr, 0) as apr,
                    coalesce(may, 0) as may,
                    coalesce(jun, 0) as jun,
                    coalesce(jul, 0) as jul,
                    coalesce(aug, 0) as aug,
                    coalesce(sep, 0) as sep,
                    coalesce(oct, 0) as oct,
                    coalesce(nov, 0) as nov,
                    coalesce("dec", 0) as "dec",
                    coalesce(jan, 0) as jan,
                    coalesce(feb, 0) as feb,
                    coalesce(mar, 0) as mar,
                    coalesce(adj1, 0) as adj1,
                    coalesce(adj2, 0) as adj2,
                    coalesce(adj3, 0) as adj3
            FROM forecast_forecast_budget_view f 
                FULL OUTER JOIN forecast_financialcode fc
                    on fc.id = f.financial_code_id;                    
        """,
            """
                DROP VIEW if exists forecast_forecast_download_view;
                """,
        )
    ]
