# Generated by Django 2.2.8 on 2020-02-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0059_edit_forecast_download_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastingDataView',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('financial_year', models.IntegerField()),
                ('budget', models.BigIntegerField(default=0)),
                ('apr', models.BigIntegerField(default=0)),
                ('may', models.BigIntegerField(default=0)),
                ('jun', models.BigIntegerField(default=0)),
                ('jul', models.BigIntegerField(default=0)),
                ('aug', models.BigIntegerField(default=0)),
                ('sep', models.BigIntegerField(default=0)),
                ('oct', models.BigIntegerField(default=0)),
                ('nov', models.BigIntegerField(default=0)),
                ('dec', models.BigIntegerField(default=0)),
                ('jan', models.BigIntegerField(default=0)),
                ('feb', models.BigIntegerField(default=0)),
                ('mar', models.BigIntegerField(default=0)),
                ('adj1', models.BigIntegerField(default=0)),
                ('adj2', models.BigIntegerField(default=0)),
                ('adj3', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'forecast_forecast_download_view',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='ForecastBudgetDataView',
        ),
    ]
