# Generated by Django 2.2.10 on 2020-05-22 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('costcentre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftAndHospitalityCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('gif_hospitality_category', models.CharField(max_length=100, verbose_name='Category')),
                ('sequence_no', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Gift and Hospitality Category',
                'verbose_name_plural': 'Gift and Hospitality Categories',
                'ordering': ['sequence_no'],
            },
        ),
        migrations.CreateModel(
            name='GiftAndHospitalityClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('gift_type', models.CharField(choices=[('Gift', 'Gift'), ('Hospitality', 'Hospitality')], default='Hospitality', max_length=20, verbose_name='Type')),
                ('gif_hospitality_classification', models.CharField(max_length=100, verbose_name='Classification')),
                ('sequence_no', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Gift and Hospitality Type',
                'verbose_name_plural': 'Gift and Hospitality Types',
                'ordering': ['sequence_no'],
            },
        ),
        migrations.CreateModel(
            name='GiftAndHospitalityCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('gif_hospitality_company', models.CharField(max_length=100, verbose_name='Company')),
                ('sequence_no', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Gift and Hospitality Company',
                'verbose_name_plural': 'Gift and Hospitality Companies',
                'ordering': ['sequence_no'],
            },
        ),
        migrations.CreateModel(
            name='GiftHospitalityPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('can_view_all_gifthospitality', 'Can view all Gift Hospitality entries'),),
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('grade', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('gradedescription', models.CharField(max_length=50, verbose_name='Grade Description')),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
            },
        ),
        migrations.CreateModel(
            name='SimpleHistoryGrade',
            fields=[
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('active', models.BooleanField(default=False)),
                ('grade', models.CharField(db_index=True, max_length=10)),
                ('gradedescription', models.CharField(max_length=50, verbose_name='Grade Description')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Grade',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SimpleHistoryGiftAndHospitalityCompany',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('active', models.BooleanField(default=False)),
                ('gif_hospitality_company', models.CharField(max_length=100, verbose_name='Company')),
                ('sequence_no', models.IntegerField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Gift and Hospitality Company',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SimpleHistoryGiftAndHospitalityClassification',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('active', models.BooleanField(default=False)),
                ('gift_type', models.CharField(choices=[('Gift', 'Gift'), ('Hospitality', 'Hospitality')], default='Hospitality', max_length=20, verbose_name='Type')),
                ('gif_hospitality_classification', models.CharField(max_length=100, verbose_name='Classification')),
                ('sequence_no', models.IntegerField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Gift and Hospitality Type',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SimpleHistoryGiftAndHospitalityCategory',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('active', models.BooleanField(default=False)),
                ('gif_hospitality_category', models.CharField(max_length=100, verbose_name='Category')),
                ('sequence_no', models.IntegerField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Gift and Hospitality Category',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SimpleHistoryGiftAndHospitality',
            fields=[
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('id', models.IntegerField(blank=True, db_index=True, verbose_name='Record ID')),
                ('old_id', models.IntegerField(blank=True, null=True)),
                ('group_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Group')),
                ('date_agreed', models.DateField(verbose_name='Date of event /  gift offered')),
                ('venue', models.CharField(max_length=1000)),
                ('reason', models.CharField(max_length=1000, verbose_name='Description of offer and reason')),
                ('value', models.IntegerField(verbose_name='Estimated value of offer (£)')),
                ('rep', models.CharField(blank=True, max_length=200, verbose_name='DIT representative offered to/from')),
                ('offer', models.CharField(choices=[('Received', 'Received by DIT Staff'), ('Offered', 'Given by DIT Staff')], max_length=200)),
                ('company_rep', models.CharField(max_length=200, verbose_name='Company representative offered to/from')),
                ('action_taken', models.CharField(blank=True, choices=[('Action1', 'Rejected'), ('Action2', 'Accepted (difference paid to Department)'), ('Action3', 'Accepted (surrendered to Department)'), ('Action0', 'Accepted')], max_length=200, verbose_name='Action taken')),
                ('entered_by', models.CharField(max_length=100)),
                ('entered_date_stamp', models.DateField(verbose_name='Date entered')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gifthospitality.GiftAndHospitalityCategory', verbose_name='category')),
                ('classification', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gifthospitality.GiftAndHospitalityClassification', verbose_name='Type')),
                ('company', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gifthospitality.GiftAndHospitalityCompany', verbose_name='company')),
                ('grade', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gifthospitality.Grade', verbose_name='grade')),
                ('group', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='costcentre.DepartmentalGroup', verbose_name='DIT Group')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Gift and Hospitality',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='GiftAndHospitality',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Record ID')),
                ('old_id', models.IntegerField(blank=True, null=True)),
                ('group_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Group')),
                ('date_agreed', models.DateField(verbose_name='Date of event /  gift offered')),
                ('venue', models.CharField(max_length=1000)),
                ('reason', models.CharField(max_length=1000, verbose_name='Description of offer and reason')),
                ('value', models.IntegerField(verbose_name='Estimated value of offer (£)')),
                ('rep', models.CharField(blank=True, max_length=200, verbose_name='DIT representative offered to/from')),
                ('offer', models.CharField(choices=[('Received', 'Received by DIT Staff'), ('Offered', 'Given by DIT Staff')], max_length=200)),
                ('company_rep', models.CharField(max_length=200, verbose_name='Company representative offered to/from')),
                ('action_taken', models.CharField(blank=True, choices=[('Action1', 'Rejected'), ('Action2', 'Accepted (difference paid to Department)'), ('Action3', 'Accepted (surrendered to Department)'), ('Action0', 'Accepted')], max_length=200, verbose_name='Action taken')),
                ('entered_by', models.CharField(max_length=100)),
                ('entered_date_stamp', models.DateField(verbose_name='Date entered')),
                ('category', models.ForeignKey(limit_choices_to={'active': True}, on_delete=django.db.models.deletion.PROTECT, to='gifthospitality.GiftAndHospitalityCategory', verbose_name='category')),
                ('classification', models.ForeignKey(limit_choices_to={'active': True}, on_delete=django.db.models.deletion.PROTECT, to='gifthospitality.GiftAndHospitalityClassification', verbose_name='Type')),
                ('company', models.ForeignKey(blank=True, limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gifthospitality.GiftAndHospitalityCompany', verbose_name='company')),
                ('grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gifthospitality.Grade', verbose_name='grade')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='costcentre.DepartmentalGroup', verbose_name='DIT Group')),
            ],
            options={
                'verbose_name': 'Gift and Hospitality',
                'verbose_name_plural': 'Gift and Hospitality',
                'ordering': ['-id'],
            },
        ),
    ]
