# Generated by Django 2.1.2 on 2018-11-08 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GiftsAndHospitality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('group_name', models.CharField(max_length=200)),
                ('date_offered', models.DateTimeField()),
                ('venue', models.CharField(max_length=1000)),
                ('reason', models.CharField(max_length=1000)),
                ('value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('band', models.CharField(max_length=50)),
                ('rep', models.CharField(max_length=255)),
                ('offer',
                 models.CharField(choices=[('Received', 'Received'), ('Offered', 'Offered')],
                                  max_length=50)),
                ('company_rep', models.CharField(max_length=50)),
                ('action_taken', models.CharField(choices=[('Action1', 'Accepted'), (
                'Action2', 'Accepted (difference paid to Department)'), ('Action3',
                                                                         'Accepted (surrendered to Department)')],
                                                  max_length=20, verbose_name='Action taken')),
                ('date_stamp', models.DateTimeField()),
                ('entered_by', models.CharField(max_length=50)),
                ('staff_no', models.CharField(max_length=50)),
                ('entered_date_stamp', models.DateTimeField(auto_now=True)),
                ('grade', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GiftsAndHospitalityCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Gifts and Hospitality Category',
                'verbose_name_plural': 'Gifts and Hospitality Categories',
            },
        ),
        migrations.CreateModel(
            name='GiftsAndHospitalityClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('gift_type',
                 models.CharField(choices=[('GIFT', 'Gift'), ('HOSPITALITY', 'Hospitality')],
                                  default='HOSPITALITY', max_length=20, verbose_name='Type')),
                ('classification', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Gift and Hospitality Classification',
                'verbose_name_plural': 'Gifts and Hospitality Classifications',
            },
        ),
        migrations.CreateModel(
            name='GiftsAndHospitalityCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Gifts and Hospitality Company',
                'verbose_name_plural': 'Gifts and Hospitality Companies',
            },
        ),
        migrations.AddField(
            model_name='giftsandhospitality',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                    to='gifthospitality.GiftsAndHospitalityCategory'),
        ),
        migrations.AddField(
            model_name='giftsandhospitality',
            name='classification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                    to='gifthospitality.GiftsAndHospitalityClassification'),
        ),
        migrations.AddField(
            model_name='giftsandhospitality',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                    to='gifthospitality.GiftsAndHospitalityCompany'),
        ),
    ]
