# Generated by Django 2.1.2 on 2018-11-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("gifthospitality", "0001_initial")]

    operations = [
        migrations.AlterModelOptions(
            name="giftsandhospitality",
            options={
                "verbose_name": "Gifts and Hospitality",
                "verbose_name_plural": "Gifts and Hospitality",
            },
        ),
        migrations.AlterField(
            model_name="giftsandhospitality",
            name="classification",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="giftsandhospitality",
            name="date_offered",
            field=models.DateField(),
        ),
    ]
