# Generated by Django 2.0.2 on 2018-09-12 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifthospitality', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftsandhospitality',
            name='group_code',
        ),
    ]
