# Generated by Django 2.0.2 on 2018-09-12 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifthospitality', '0002_remove_giftsandhospitality_group_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftsandhospitality',
            name='grade',
        ),
        migrations.DeleteModel(
            name='GiftsAndHospitality',
        ),
    ]
