# Generated by Django 2.1.2 on 2018-11-23 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifthospitality', '0004_auto_20181123_0859'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GiftsAndHospitality',
        ),
        migrations.DeleteModel(
            name='GiftsAndHospitalityCategory',
        ),
        migrations.DeleteModel(
            name='GiftsAndHospitalityClassification',
        ),
        migrations.DeleteModel(
            name='GiftsAndHospitalityCompany',
        ),
    ]
