# Generated by Django 2.1.2 on 2018-11-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("gifthospitality", "0005_auto_20181123_0901")]

    operations = [
        migrations.AlterField(
            model_name="giftandhospitality",
            name="id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="Record ID"
            ),
        )
    ]
