# Generated by Django 2.1.2 on 2018-11-27 11:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("gifthospitality", "0006_auto_20181123_1204")]

    operations = [
        migrations.RemoveField(model_name="giftandhospitality", name="date_stamp")
    ]
