# Generated by Django 2.1.2 on 2018-12-03 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("payroll", "0003_auto_20181203_1524"),
        ("gifthospitality", "0010_auto_20181203_1524"),
    ]

    operations = [
        migrations.AddField(
            model_name="giftandhospitality",
            name="rep_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payroll.DITPeople",
                verbose_name="DIT Representative",
            ),
        ),
        migrations.AlterField(
            model_name="giftandhospitality",
            name="action_taken",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Action1", "Accepted"),
                    ("Action2", "Accepted (difference paid to Department)"),
                    ("Action3", "Accepted (surrendered to Department)"),
                ],
                max_length=20,
                verbose_name="Action taken",
            ),
        ),
        migrations.AlterField(
            model_name="giftandhospitality",
            name="rep",
            field=models.CharField(max_length=255, verbose_name="DIT Representative"),
        ),
    ]
