# Generated by Django 2.1.2 on 2018-12-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifthospitality', '0013_auto_20181203_1823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='giftandhospitality',
            options={'ordering': ['id'], 'verbose_name': 'Gift and Hospitality', 'verbose_name_plural': 'Gift and Hospitality'},
        ),
        migrations.AlterField(
            model_name='giftandhospitality',
            name='action_taken',
            field=models.CharField(blank=True, choices=[('Action1', 'Rejected'), ('Action2', 'Accepted (difference paid to Department)'), ('Action3', 'Accepted (surrendered to Department)'), ('Action0', 'Accepted')], max_length=20, verbose_name='Action taken'),
        ),
        migrations.AlterField(
            model_name='giftandhospitality',
            name='company',
            field=models.CharField(max_length=100, verbose_name='Company offered to/from'),
        ),
        migrations.AlterField(
            model_name='giftandhospitality',
            name='company_rep',
            field=models.CharField(max_length=50, verbose_name='Company representative offered to/from'),
        ),
        migrations.AlterField(
            model_name='giftandhospitality',
            name='date_offered',
            field=models.DateField(verbose_name='Date of event /  gift offered'),
        ),
        migrations.AlterField(
            model_name='giftandhospitality',
            name='entered_date_stamp',
            field=models.DateTimeField(auto_now=True, verbose_name='Date entered'),
        ),
        migrations.AlterField(
            model_name='giftandhospitality',
            name='gift_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Classification'),
        ),
        migrations.AlterField(
            model_name='giftandhospitality',
            name='group_name',
            field=models.CharField(max_length=200, verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='giftandhospitality',
            name='offer',
            field=models.CharField(choices=[('Received', 'Received by DIT Staff'), ('Offered', 'Given by DIT Staff')], max_length=50),
        ),
        migrations.AlterField(
            model_name='giftandhospitality',
            name='reason',
            field=models.CharField(max_length=1000, verbose_name='Description of offer and reason'),
        ),
        migrations.AlterField(
            model_name='giftandhospitality',
            name='rep',
            field=models.CharField(max_length=255, verbose_name='DIT representative offered to/from'),
        ),
        migrations.AlterField(
            model_name='giftandhospitalityclassification',
            name='gift_type',
            field=models.CharField(choices=[('Gifts', 'Gift'), ('Hospitality', 'Hospitality')], default='Hospitality', max_length=20, verbose_name='Type'),
        ),
    ]
