# Generated by Django 2.1.2 on 2018-12-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifthospitality', '0019_auto_20181217_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftandhospitality',
            name='action_taken',
            field=models.CharField(blank=True, choices=[('Action1', 'Rejected'), ('Action2', 'Accepted (difference paid to Department)'), ('Action3', 'Accepted (surrendered to Department)'), ('Action0', 'Accepted')], max_length=200, verbose_name='Action taken'),
        ),
    ]
