# Generated by Django 2.1.2 on 2018-12-24 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("gifthospitality", "0023_auto_20181224_1350")]

    operations = [
        migrations.RemoveField(model_name="giftandhospitality", name="category")
    ]
