# Generated by Django 2.1.2 on 2018-12-24 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifthospitality', '0025_auto_20181224_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftandhospitality',
            name='classification',
        ),
        migrations.RemoveField(
            model_name='giftandhospitality',
            name='gift_type',
        ),
    ]
