# Generated by Django 2.1.2 on 2018-12-24 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_auto_20181211_1600'),
        ('gifthospitality', '0026_auto_20181224_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftandhospitality',
            name='grade_fk',
            field=models.ForeignKey(default='SEO', on_delete=django.db.models.deletion.PROTECT, to='payroll.Grade', verbose_name='grade'),
            preserve_default=False,
        ),
    ]
