# Generated by Django 2.2.10 on 2020-02-14 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll', '0005_auto_20200214_1117'),
        ('gifthospitality', '0028_remove_giftandhospitality_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftandhospitality',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='giftandhospitality',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='SimpleHistoryGiftAndHospitalityCompany',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('active', models.BooleanField(default=False)),
                ('gif_hospitality_company', models.CharField(max_length=100, verbose_name='Company')),
                ('sequence_no', models.IntegerField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Gift and Hospitality Company',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SimpleHistoryGiftAndHospitalityClassification',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('active', models.BooleanField(default=False)),
                ('gift_type', models.CharField(choices=[('Gift', 'Gift'), ('Hospitality', 'Hospitality')], default='Hospitality', max_length=20, verbose_name='Type')),
                ('gif_hospitality_classification', models.CharField(max_length=100, verbose_name='Classification')),
                ('sequence_no', models.IntegerField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Gift and Hospitality Type',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SimpleHistoryGiftAndHospitalityCategory',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('active', models.BooleanField(default=False)),
                ('gif_hospitality_category', models.CharField(max_length=100, verbose_name='Category')),
                ('sequence_no', models.IntegerField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Gift and Hospitality Category',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SimpleHistoryGiftAndHospitality',
            fields=[
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('id', models.IntegerField(blank=True, db_index=True, verbose_name='Record ID')),
                ('old_id', models.IntegerField(blank=True, null=True)),
                ('group_name', models.CharField(max_length=200, verbose_name='Group')),
                ('date_offered', models.DateField(verbose_name='Date of event /  gift offered')),
                ('venue', models.CharField(max_length=1000)),
                ('reason', models.CharField(max_length=1000, verbose_name='Description of offer and reason')),
                ('value', models.IntegerField(verbose_name='Estimated value of offer (£)')),
                ('rep', models.CharField(max_length=255, verbose_name='DIT representative offered to/from')),
                ('offer', models.CharField(choices=[('Received', 'Received by DIT Staff'), ('Offered', 'Given by DIT Staff')], max_length=200)),
                ('company_rep', models.CharField(max_length=200, verbose_name='Company representative offered to/from')),
                ('company', models.CharField(max_length=200, verbose_name='Company offered to/from')),
                ('action_taken', models.CharField(blank=True, choices=[('Action1', 'Rejected'), ('Action2', 'Accepted (difference paid to Department)'), ('Action3', 'Accepted (surrendered to Department)'), ('Action0', 'Accepted')], max_length=200, verbose_name='Action taken')),
                ('entered_by', models.CharField(max_length=100)),
                ('entered_date_stamp', models.DateField(verbose_name='Date entered')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category_fk', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gifthospitality.GiftAndHospitalityCategory', verbose_name='category')),
                ('classification_fk', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gifthospitality.GiftAndHospitalityClassification', verbose_name='Type')),
                ('company_fk', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gifthospitality.GiftAndHospitalityCompany', verbose_name='company')),
                ('grade_fk', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='payroll.Grade', verbose_name='grade')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('rep_fk', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='payroll.DITPeople', verbose_name='DIT Representative')),
            ],
            options={
                'verbose_name': 'historical Gift and Hospitality',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
