# Generated by Django 2.2.10 on 2020-04-02 09:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gifthospitality', '0031_auto_20200402_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftandhospitality',
            name='group',
            field=models.CharField(default='DEFAULT', max_length=255, verbose_name='DIT Group offered to/from'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='simplehistorygiftandhospitality',
            name='group',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='DIT Group offered to/from'),
            preserve_default=False,
        ),
    ]
