# Generated by Django 2.2.10 on 2020-04-07 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('costcentre', '0030_auto_20200214_1117'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gifthospitality', '0033_auto_20200402_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='DITGroup',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('group_display_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('cost_centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='costcentre.CostCentre')),
                ('directorate_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='costcentre.Directorate')),
                ('group_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='costcentre.DepartmentalGroup')),
            ],
            options={
                'verbose_name': 'DIT Group',
                'verbose_name_plural': 'DIT Group',
                'ordering': ['cost_centre'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('grade', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('gradedescription', models.CharField(max_length=50, verbose_name='Grade Description')),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
            },
        ),
        migrations.AlterField(
            model_name='giftandhospitality',
            name='grade_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gifthospitality.Grade', verbose_name='grade'),
        ),
        migrations.AlterField(
            model_name='giftandhospitality',
            name='group_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gifthospitality.DITGroup', verbose_name='DIT Group'),
        ),
        migrations.AlterField(
            model_name='simplehistorygiftandhospitality',
            name='grade_fk',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gifthospitality.Grade', verbose_name='grade'),
        ),
        migrations.AlterField(
            model_name='simplehistorygiftandhospitality',
            name='group_fk',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gifthospitality.DITGroup', verbose_name='DIT Group'),
        ),
        migrations.CreateModel(
            name='SimpleHistoryGrade',
            fields=[
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('grade', models.CharField(db_index=True, max_length=10)),
                ('gradedescription', models.CharField(max_length=50, verbose_name='Grade Description')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Grade',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SimpleHistoryDITGroup',
            fields=[
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('active', models.BooleanField(default=False)),
                ('group_display_name', models.CharField(db_index=True, max_length=50)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cost_centre', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='costcentre.CostCentre')),
                ('directorate_code', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='costcentre.Directorate')),
                ('group_code', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='costcentre.DepartmentalGroup')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical DIT Group',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
