# Generated by Django 2.2.10 on 2020-04-08 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifthospitality', '0034_auto_20200407_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='giftandhospitality',
            old_name='classification_fk',
            new_name='classification',
        ),
        migrations.RenameField(
            model_name='simplehistorygiftandhospitality',
            old_name='classification_fk',
            new_name='classification',
        ),
    ]
