# Generated by Django 2.2.10 on 2020-04-08 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifthospitality', '0035_auto_20200408_0819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='giftandhospitality',
            old_name='category_fk',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='simplehistorygiftandhospitality',
            old_name='category_fk',
            new_name='category',
        ),
    ]
