# Generated by Django 2.2.10 on 2020-04-08 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifthospitality', '0036_auto_20200408_0822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='giftandhospitality',
            old_name='grade_fk',
            new_name='grade',
        ),
        migrations.RenameField(
            model_name='simplehistorygiftandhospitality',
            old_name='grade_fk',
            new_name='grade',
        ),
    ]
