# Generated by Django 2.2.10 on 2020-04-08 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifthospitality', '0037_auto_20200408_0825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftandhospitality',
            name='group_fk',
        ),
        migrations.RemoveField(
            model_name='simplehistorygiftandhospitality',
            name='group_fk',
        ),
    ]
