# Generated by Django 2.2.10 on 2020-04-08 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gifthospitality', '0038_auto_20200408_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftandhospitality',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gifthospitality.DITGroup', verbose_name='DIT Group'),
        ),
        migrations.AlterField(
            model_name='simplehistorygiftandhospitality',
            name='group',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gifthospitality.DITGroup', verbose_name='DIT Group'),
        ),
    ]
