# Generated by Django 2.2.10 on 2020-04-08 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifthospitality', '0040_auto_20200408_0830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftandhospitality',
            name='company_fk',
        ),
        migrations.RemoveField(
            model_name='simplehistorygiftandhospitality',
            name='company_fk',
        ),
    ]
