# Generated by Django 2.2.10 on 2020-04-08 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gifthospitality', '0041_auto_20200408_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftandhospitality',
            name='company',
            field=models.ForeignKey(blank=True, limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gifthospitality.GiftAndHospitalityCompany', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='simplehistorygiftandhospitality',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gifthospitality.GiftAndHospitalityCompany', verbose_name='company'),
        ),
    ]
