# Generated by Django 2.2.10 on 2020-04-15 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gifthospitality', '0043_auto_20200415_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftandhospitality',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='costcentre.DepartmentalGroup', verbose_name='DIT Cost Centre'),
        ),
        migrations.AlterField(
            model_name='simplehistorygiftandhospitality',
            name='group',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='costcentre.DepartmentalGroup', verbose_name='DIT Cost Centre'),
        ),
    ]
