# Generated by Django 2.2.10 on 2020-04-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifthospitality', '0045_auto_20200415_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='simplehistorygrade',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
