# Generated by Django 2.2.10 on 2020-04-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifthospitality', '0049_create_gifthospitality_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftHospitalityPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('can_view_gifthospitality', 'Can view all Gift Hospitality entries'),),
            },
        ),
    ]
