# Generated by Django 2.2.13 on 2020-08-24 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_data_20200810'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('costcentre', '0002_auto_20200603_1555'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricCostCentre',
            new_name='ArchivedCostCentre',
        ),
        migrations.RenameModel(
            old_name='SimpleHistoryHistoricCostCentre',
            new_name='SimpleHistoryArchivedCostCentre',
        ),
        migrations.AlterModelOptions(
            name='simplehistoryarchivedcostcentre',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Archived Cost Centre'},
        ),
    ]
