# Generated by Django 2.1.2 on 2018-11-01 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('costcentre', '0005_auto_20181101_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='costcentre',
            name='bsce_email',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.PROTECT,
                                    to='costcentre.BSCEEmail', verbose_name='BSCE Email'),
        ),
    ]
