# Generated by Django 2.1.2 on 2018-11-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('costcentre', '0007_businesspartner'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCentrePerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('email',
                 models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('is_director', models.BooleanField(default=False, verbose_name='Director')),
                ('is_dg', models.BooleanField(default=False, verbose_name='General Director')),
            ],
            options={
                'verbose_name': 'Cost Centre Person',
                'verbose_name_plural': 'Cost Centre People',
            },
        ),
        migrations.RemoveField(
            model_name='businesspartner',
            name='full_name',
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='surname',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
