# Generated by Django 2.1.2 on 2018-11-05 11:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('costcentre', '0010_auto_20181101_1711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='costcentreperson',
            options={'verbose_name': 'Hierarchy Responsibility',
                     'verbose_name_plural': 'Hierarchy Responsibilities'},
        ),
    ]
