# Generated by Django 2.1.2 on 2018-11-23 08:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('costcentre', '0013_auto_20181108_1706'),
        ('costcentre', '0013_auto_20181109_1253'),
    ]

    operations = [
    ]
