# Generated by Django 2.1.2 on 2018-11-23 08:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('costcentre', '0014_merge_20181123_0859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bsceemail',
            options={'ordering': ['bsce_email'], 'verbose_name': 'BSCE Email',
                     'verbose_name_plural': 'BSCE Emails'},
        ),
        migrations.AlterModelOptions(
            name='businesspartner',
            options={'ordering': ['surname', 'name'], 'verbose_name': 'Business Partner',
                     'verbose_name_plural': 'Business Partners'},
        ),
        migrations.AlterModelOptions(
            name='costcentre',
            options={'ordering': ['cost_centre_code'], 'verbose_name': 'Cost Centre',
                     'verbose_name_plural': 'Cost Centres'},
        ),
        migrations.AlterModelOptions(
            name='departmentalgroup',
            options={'ordering': ['group_code'], 'verbose_name': 'Departmental Group',
                     'verbose_name_plural': 'Departmental Groups'},
        ),
        migrations.AlterModelOptions(
            name='directorate',
            options={'ordering': ['directorate_code'], 'verbose_name': 'Directorate',
                     'verbose_name_plural': 'Directorates'},
        ),
    ]
