# Generated by Django 2.2 on 2019-06-21 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costcentre', '0025_costcentre_subsegment_mapping'),
    ]

    # operations = [
    #     migrations.RemoveField(
    #         model_name='costcentre',
    #         name='subsegment_mapping',
    #     ),
    # ]
