# Generated by Django 2.2 on 2019-06-24 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("treasurySS", "0104_auto_20190624_1445"),
        ("costcentre", "0026_remove_costcentre_subsegment_mapping"),
    ]

    operations = [
        migrations.AddField(
            model_name="departmentalgroup",
            name="treasury_segment_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="treasurySS.Segment",
            ),
        )
    ]
