# Generated by Django 2.2 on 2019-07-02 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("costcentre", "0027_departmentalgroup_treasury_segment_fk")]

    operations = [
        migrations.AlterField(
            model_name="costcentre",
            name="used_for_travel",
            field=models.BooleanField(default="True", verbose_name="Used for Travel"),
        ),
        migrations.AlterField(
            model_name="departmentalgroup",
            name="treasury_segment_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="treasurySS.Segment",
                verbose_name="Treasury Segment",
            ),
        ),
    ]
