# Generated by Django 2.2.10 on 2020-04-03 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costcentre', '0030_auto_20200214_1117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='costcentre',
            options={'default_permissions': ('change',), 'ordering': ['cost_centre_code'], 'permissions': (('edit_forecast_all_cost_centres', 'Edit all cost centres'), ('assign_edit_for_own_cost_centres', 'Assign edit cost centre for own cost centres')), 'verbose_name': 'Cost Centre', 'verbose_name_plural': 'Cost Centres'},
        ),
    ]
