# Generated by Django 2.0.2 on 2018-06-11 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostCentre',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cost_centre_code', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='cost centre')),
                ('cost_centre_name', models.CharField(max_length=300, verbose_name='description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DepartmentalGroup',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('group_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Directorate',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('directorate_code', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Directorate')),
                ('directorate_name', models.CharField(max_length=300)),
                ('group_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='costcentre.DepartmentalGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('programme_code', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Programme Code')),
                ('programme_description', models.CharField(max_length=100, verbose_name='Description')),
                ('budget_type', models.CharField(max_length=100, verbose_name='Budget Type')),
            ],
        ),
        migrations.AddField(
            model_name='costcentre',
            name='directorate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='costcentre.Directorate'),
        ),
    ]
