# Generated by Django 2.0.2 on 2018-08-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostCentre',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cost_centre_code', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Cost Centre Code')),
                ('cost_centre_name', models.CharField(max_length=300, verbose_name='Cost Centre Name')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DepartmentalGroup',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('group_code', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Group')),
                ('group_name', models.CharField(max_length=300, verbose_name='Group Name')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Directorate',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('directorate_code', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Directorate')),
                ('directorate_name', models.CharField(max_length=300, verbose_name='Directorate Name')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('programme_code', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Programme Code')),
                ('programme_description', models.CharField(max_length=100, verbose_name='Programme Name')),
                ('budget_type', models.CharField(max_length=100, verbose_name='Budget Type')),
                ('DIT_in_use', models.BooleanField(default=True, verbose_name='Used by DIT')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
