# Generated by Django 2.0.2 on 2018-07-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costcentre', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costcentre',
            name='cost_centre_code',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Cost centre'),
        ),
        migrations.AlterField(
            model_name='departmentalgroup',
            name='group_code',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='directorate',
            name='directorate_code',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Directorate'),
        ),
    ]
