# Generated by Django 2.0.2 on 2018-07-11 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costcentre', '0002_auto_20180704_1136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directorate',
            old_name='group_code',
            new_name='group',
        ),
    ]
