# Generated by Django 2.0.2 on 2018-08-16 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_auto_20180816_1111'),
        ('costcentre', '0003_auto_20180711_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='costcentre',
            name='business_partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='business_partner', to='payroll.DITPeople'),
        ),
        migrations.AddField(
            model_name='costcentre',
            name='deputy_director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deputy_director', to='payroll.DITPeople'),
        ),
        migrations.AddField(
            model_name='departmentalgroup',
            name='director_general',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='payroll.DITPeople'),
        ),
        migrations.AddField(
            model_name='directorate',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='payroll.DITPeople'),
        ),
        migrations.AlterField(
            model_name='costcentre',
            name='cost_centre_code',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Cost Centre Code'),
        ),
        migrations.AlterField(
            model_name='costcentre',
            name='cost_centre_name',
            field=models.CharField(max_length=300, verbose_name='Cost Centre Description'),
        ),
    ]
