# Generated by Django 2.0.2 on 2018-08-29 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costcentre', '0003_auto_20180828_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costcentre',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='departmentalgroup',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='directorate',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='directorate',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payroll.DITPeople'),
        ),
        migrations.AlterField(
            model_name='programme',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
