# Generated by Django 2.0.2 on 2018-08-29 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costcentre', '0004_auto_20180829_0723'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='costcentre',
            options={'verbose_name': 'Cost Centre', 'verbose_name_plural': 'Cost Centres'},
        ),
        migrations.AlterModelOptions(
            name='departmentalgroup',
            options={'verbose_name': 'Departmental Group', 'verbose_name_plural': 'Departmental Groups'},
        ),
        migrations.AlterModelOptions(
            name='directorate',
            options={'verbose_name': 'Directorate', 'verbose_name_plural': 'Directorates'},
        ),
        migrations.AlterModelOptions(
            name='programme',
            options={'verbose_name': 'Programme Code', 'verbose_name_plural': 'Programme Codes'},
        ),
    ]
