# Generated by Django 2.0.2 on 2018-08-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costcentre', '0004_auto_20180816_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='in_use',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='costcentre',
            name='cost_centre_name',
            field=models.CharField(max_length=300, verbose_name='Cost Centre Name'),
        ),
        migrations.AlterField(
            model_name='departmentalgroup',
            name='group_name',
            field=models.CharField(max_length=300, verbose_name='Group Name'),
        ),
        migrations.AlterField(
            model_name='directorate',
            name='directorate_name',
            field=models.CharField(max_length=300, verbose_name='Directorate Name'),
        ),
        migrations.AlterField(
            model_name='programme',
            name='programme_description',
            field=models.CharField(max_length=100, verbose_name='Programme Name'),
        ),
    ]
