# Generated by Django 2.0.2 on 2018-08-20 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costcentre', '0005_auto_20180816_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programme',
            name='in_use',
        ),
        migrations.AddField(
            model_name='departmentalgroup',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='directorate',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='programme',
            name='DIT_in_use',
            field=models.BooleanField(default=True, verbose_name='Used by DIT'),
        ),
        migrations.AlterField(
            model_name='costcentre',
            name='business_partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='business_partner', to='payroll.DITPeople', verbose_name='Finance Business Partner'),
        ),
    ]
