# Generated by Django 2.0.2 on 2018-08-29 14:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('gifthospitality', '0004_auto_20180829_1432'),
        ('payroll', '0004_auto_20180829_1432'),
        ('costcentre', '0005_auto_20180829_0936'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Programme',
        ),
    ]
