# Generated by Django 2.0.2 on 2018-08-20 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costcentre', '0006_auto_20180820_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costcentre',
            name='deputy_director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deputy_director', to='payroll.DITPeople'),
        ),
    ]
