# Generated by Django 2.2.4 on 2019-11-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='processed',
        ),
        migrations.AddField(
            model_name='fileupload',
            name='error_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='status',
            field=models.CharField(choices=[('unprocessed', 'Unprocessed'), ('processing', 'Processing'), ('processed', 'Processed'), ('error', 'Error')], default='unprocessed', max_length=11),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='user_error_message',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
