# Generated by Django 2.2.10 on 2020-03-05 15:50

from django.db import migrations, models
import s3chunkuploader.fields


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='document_file',
            field=s3chunkuploader.fields.S3FileField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='simplehistoryfileupload',
            name='document_file',
            field=models.TextField(max_length=1000),
        ),
    ]
