# Generated by Django 2.2.10 on 2020-04-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0002_auto_20200305_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='row_process_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='user_warning_message',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='simplehistoryfileupload',
            name='row_process_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='simplehistoryfileupload',
            name='user_warning_message',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='status',
            field=models.CharField(choices=[('unprocessed', 'Unprocessed'), ('antivirus', 'Checking for viruses'), ('processing', 'Processing'), ('Parsing', 'Processing after error'), ('processed', 'Processed'), ('error', 'Error')], default='unprocessed', max_length=11),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='user_error_message',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='simplehistoryfileupload',
            name='status',
            field=models.CharField(choices=[('unprocessed', 'Unprocessed'), ('antivirus', 'Checking for viruses'), ('processing', 'Processing'), ('Parsing', 'Processing after error'), ('processed', 'Processed'), ('error', 'Error')], default='unprocessed', max_length=11),
        ),
        migrations.AlterField(
            model_name='simplehistoryfileupload',
            name='user_error_message',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
