# Generated by Django 2.2.10 on 2020-05-09 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0004_auto_20200504_1313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileupload',
            options={'permissions': [('can_upload_admin', 'Can upload in Admin')]},
        ),
    ]
