# Generated by Django 2.2.4 on 2019-11-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0004_uploadpermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='status',
            field=models.CharField(choices=[('unprocessed', 'Unprocessed'), ('antivirus', 'Checking for viruses'), ('processing', 'Processing'), ('processed', 'Processed'), ('error', 'Error')], default='unprocessed', max_length=11),
        ),
    ]
