# Generated by Django 2.2.4 on 2019-11-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0005_auto_20191114_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadpermission',
            name='upload_actuals',
        ),
        migrations.RemoveField(
            model_name='uploadpermission',
            name='upload_budget',
        ),
        migrations.AddField(
            model_name='fileupload',
            name='document_type',
            field=models.CharField(choices=[('actuals', 'Actuals'), ('budget', 'Budget')], default='actuals', max_length=7),
        ),
    ]
