# Generated by Django 2.2.4 on 2019-11-15 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0006_auto_20191114_1346'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadPermission',
        ),
    ]
