# Generated by Django 2.2.4 on 2019-11-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0007_delete_uploadpermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='user_error_message',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
