# Generated by Django 2.2.10 on 2020-05-22 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleHistoryFileDownload',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('document_type', models.CharField(choices=[('Oscar', 'OSCAR Return'), ('Forecast', 'Forecast'), ('Budget', 'Budget')], default='Forecast', max_length=70)),
                ('status', models.CharField(choices=[('unprocessed', 'Unprocessed'), ('downloaded', 'Downloaded'), ('error', 'Error')], default='unprocessed', max_length=11)),
                ('user_error_message', models.CharField(blank=True, max_length=1000, null=True)),
                ('error_message', models.CharField(blank=True, max_length=255, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('downloading_user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical file download',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='FileDownload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('Oscar', 'OSCAR Return'), ('Forecast', 'Forecast'), ('Budget', 'Budget')], default='Forecast', max_length=70)),
                ('status', models.CharField(choices=[('unprocessed', 'Unprocessed'), ('downloaded', 'Downloaded'), ('error', 'Error')], default='unprocessed', max_length=11)),
                ('user_error_message', models.CharField(blank=True, max_length=1000, null=True)),
                ('error_message', models.CharField(blank=True, max_length=255, null=True)),
                ('downloading_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
