# Generated by Django 2.2.8 on 2020-02-01 10:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('download_file', '0002_historicalfiledownload'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalFileDownload',
            new_name='SimpleHistoryFileDownload',
        ),
    ]
