# Generated by Django 2.2.10 on 2020-04-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download_file', '0003_auto_20200201_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedownload',
            name='document_type',
            field=models.CharField(choices=[('Oscar', 'OSCAR Return'), ('Forecast', 'Budget')], default='Forecast', max_length=70),
        ),
        migrations.AlterField(
            model_name='simplehistoryfiledownload',
            name='document_type',
            field=models.CharField(choices=[('Oscar', 'OSCAR Return'), ('Forecast', 'Budget')], default='Forecast', max_length=70),
        ),
    ]